### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[e06d993](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/e06d9932a733273a6af1cfc19414702bca3657cc)_: 

:clock10: **Pending**: waiting for processors ([14](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 14 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[e06d993](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/e06d9932a733273a6af1cfc19414702bca3657cc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2304) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C26%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201911261328586815-2304%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VOqwSMc1cCoo2dnLTLwkFf%2BGrjutNLWVejCBlfqgyTg%3D&st=2019-11-26T13%3A24%3A40Z&se=2019-12-27T13%3A29%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[5e2f62a](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/5e2f62a0a4235b0ed7cdc1c3b5c11b3ffeb1d7c4)_: 

:clock10: **Pending**: waiting for processors ([14](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 14 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[5e2f62a](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/5e2f62a0a4235b0ed7cdc1c3b5c11b3ffeb1d7c4)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C26%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201911261330091461-2304%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eJZkt9R%2BomuAnOtFL0AXoRV4oooLA8n4sNn2qhQYTs0%3D&st=2019-11-26T13%3A25%3A52Z&se=2019-12-27T13%3A30%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
