### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[df33d21](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/df33d2141bf68d9a5a3af66e904fa2fa10ba3070)_: 

:clock10: **Pending**: waiting for processors ([13](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 13 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[df33d21](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/df33d2141bf68d9a5a3af66e904fa2fa10ba3070)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-4950) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C8%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004081104381706-4950%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=J5ni1td68zsewpCV%2FxhvwutZ3Gps87ILeNawaSipdqQ%3D&st=2020-04-08T11%3A00%3A12Z&se=2020-05-09T11%3A05%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[92cafa4](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/92cafa4616ee609bf2d78efa2d9733bcd1383962)_: 

:clock10: **Pending**: waiting for processors ([13](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 13 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[92cafa4](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/92cafa4616ee609bf2d78efa2d9733bcd1383962)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C8%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004081105365112-4950%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vUVg%2FqCSFYZUMsa8NgjYPIzE70Nb8RY09NNn%2FYt52v8%3D&st=2020-04-08T11%3A01%3A29Z&se=2020-05-09T11%3A06%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
