### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[fd6bea7](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/fd6bea7b4bd29898f49971fd34ba5c7a02c0138c)_: 

:clock10: **Pending**: waiting for processors ([6](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[fd6bea7](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/fd6bea7b4bd29898f49971fd34ba5c7a02c0138c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-3306) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C20%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001201103212528-3306%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TsGn9TqcB2SjsL9T2RRRBxePS%2F9GCPaJXs7eiHpmQ14%3D&st=2020-01-20T10%3A59%3A04Z&se=2020-02-20T11%3A04%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[86133e9](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/86133e9faf208be7d84a9c66e9efef74dbd47d0e)_: 

:clock10: **Pending**: waiting for processors ([6](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[86133e9](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/86133e9faf208be7d84a9c66e9efef74dbd47d0e)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C20%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001201104154156-3306%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HK2vTf3AmINKVZy2Yj11xhjhqsTa0rhnbi3zCKaBPZ8%3D&st=2020-01-20T11%3A00%3A04Z&se=2020-02-20T11%3A05%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
