### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[9c0f4d9](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9c0f4d9efa1fbcd747c80eebd00069aa37eb00fb)_: 

:clock10: **Pending**: waiting for processors ([7](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 7 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[9c0f4d9](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9c0f4d9efa1fbcd747c80eebd00069aa37eb00fb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2357) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C28%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201911281234434388-2357%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6Ql9a05dkwq47NstRoDu0wreGuNsJ%2FI9BUwXn4Oop6w%3D&st=2019-11-28T12%3A30%3A23Z&se=2019-12-29T12%3A35%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[3114f56](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/3114f5623931e881503d1a280fe55b36e3c95ace)_: 

:clock10: **Pending**: waiting for processors ([7](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 7 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[3114f56](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/3114f5623931e881503d1a280fe55b36e3c95ace)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C28%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201911281235520897-2357%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UmSzuXcwZJ245S8bMJ2kFbcWBO23LvvxkeqEJ3rR61w%3D&st=2019-11-28T12%3A31%3A44Z&se=2019-12-29T12%3A36%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
