### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[002f179](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/002f1796599df785cc9a52851c491e04bd365654)_: 

:clock10: **Pending**: waiting for processors ([8](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[002f179](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/002f1796599df785cc9a52851c491e04bd365654)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2207) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C20%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201911201103194689-2207%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VrBljNUFM0aIHurkoELIPSQ2EPrZpfnAT8kiUup2kQY%3D&st=2019-11-20T10%3A58%3A59Z&se=2019-12-21T11%3A03%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[f5a59fe](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/f5a59fe3fa1762971bbdfa4d5a960169821f048d)_: 

:clock10: **Pending**: waiting for processors ([8](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[f5a59fe](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/f5a59fe3fa1762971bbdfa4d5a960169821f048d)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C20%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201911201104159786-2207%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1ZdRsBYbEJHQ8az2rM26cbL1C9Z3sCue8Qzi3YSk7uk%3D&st=2019-11-20T10%3A59%3A53Z&se=2019-12-21T11%3A04%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
