### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[210dcd6](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/210dcd66a884fe74ed0f8575cfcf12dd0649e3ef)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[210dcd6](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/210dcd66a884fe74ed0f8575cfcf12dd0649e3ef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2449) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C4%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912041103490879-2449%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=puh%2BbgaLP4RO5x4UzEJ4xNQ%2BGsBpaCIUUyTV9uEh%2FMg%3D&st=2019-12-04T10%3A59%3A41Z&se=2020-01-04T11%3A04%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[ac3bf50](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/ac3bf50bd89ff73eda406450d3e303fd8ee74d26)_: 

:clock10: **Pending**: waiting for processors ([9](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[ac3bf50](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/ac3bf50bd89ff73eda406450d3e303fd8ee74d26)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C4%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912041105484078-2449%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ELJcG7ENYz7v8pIZqrqRTdA9frqusvjf9Zzpm6iXScc%3D&st=2019-12-04T11%3A01%3A36Z&se=2020-01-04T11%3A06%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
