### PR TITLE
Incremental PR: add a resource and delete the added resource

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[0353617](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/03536174aa0ea36113fdf29bbe717f112b03236e)_: 

:clock10: **Pending**: waiting for processors ([8](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[0353617](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/03536174aa0ea36113fdf29bbe717f112b03236e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/incrementalPR-addresource.jpg](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addresource/E2E_DocsBranch_Dynamic/incrementalPR-addresource.jpg) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/incrementalpr-addresource.jpg?branch=pr-en-us-4287) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C10%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003101135072873-4287%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rqBm1jXEKmmmbN%2F5zSE4vzElRfVH28gJmOnt6jNaUtE%3D&st=2020-03-10T11%3A30%3A44Z&se=2020-04-10T11%3A35%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[5ce6873](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/5ce68739b5ee413ca4491a976178dd0049c41302)_: 

:clock10: **Pending**: waiting for processors ([8](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[5ce6873](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/5ce68739b5ee413ca4491a976178dd0049c41302)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C10%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003101136114880-4287%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OqelwWAVOqe73eFZHTLXoF5tQ05%2BKzesf6SBwPEFneE%3D&st=2020-03-10T11%3A31%3A45Z&se=2020-04-10T11%3A36%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
