### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[4824d53](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/4824d5341174c45c8c9bd92380275611c2e57b73)_: 

:clock10: **Pending**: waiting for processors ([18](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 18 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[4824d53](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/4824d5341174c45c8c9bd92380275611c2e57b73)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-4468) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C18%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003181104137056-4468%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=y%2FIgXcQEQbNq%2BV8OMqXAMhJfOOqKRLMvFq8t9ei%2FaQI%3D&st=2020-03-18T10%3A59%3A50Z&se=2020-04-18T11%3A04%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[3b8dc10](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/3b8dc10b1775e3d251b448cc1cfc2a703008c4bb)_: 

:clock10: **Pending**: waiting for processors ([7](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 7 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[3b8dc10](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/3b8dc10b1775e3d251b448cc1cfc2a703008c4bb)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C18%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003181105248041-4468%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5pkbp6nG3PyA%2FPE5L7IgkW0g6ypZIft0cSHWWsKcj0I%3D&st=2020-03-18T11%3A01%3A33Z&se=2020-04-18T11%3A06%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
