### PR TITLE
Update skip-level.md

### PR DESCRIPTION
**Pull request by luyajun0205**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[5bb3dc3](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/5bb3dc3e302d49a049f61b5b2aa68bcf1fe8c954)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/pr-only/includes/skip-level.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/pronly-on-skipLevel-suggestion/E2E_DocsBranch_Dynamic/pr-only/includes/skip-level.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/pr-only/[pr-only%202]%20unchanged%20file%20with%20more%20log?branch=pr-en-us-7248) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C7%5C24%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202007240556449716-7248%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iCIzU5Wm4l8cpWmHae299rkmdyjwPTyEd49RJYcNZaw%3D&st=2020-07-24T05%3A52%3A19Z&se=2020-08-24T05%3A57%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://opportal-sandbox.azurewebsites.net/#/repos/8b165afe-a866-8c48-e5c3-ead94440f27e?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[5bb3dc3](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/5bb3dc3e302d49a049f61b5b2aa68bcf1fe8c954)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/pr-only/includes/skip-level.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/pronly-on-skipLevel-suggestion/E2E_DocsBranch_Dynamic/pr-only/includes/skip-level.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/pr-only/[pr-only%202]%20unchanged%20file%20with%20more%20log?branch=pr-en-us-7248) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C7%5C24%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202007240616340056-7248%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RFrGTMte5zYDvRMkLdKn63e3ZgluC37sir4lkETD%2Fx8%3D&st=2020-07-24T06%3A12%3A26Z&se=2020-08-24T06%3A17%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://opportal-sandbox.azurewebsites.net/#/repos/8b165afe-a866-8c48-e5c3-ead94440f27e?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[1f859dc](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/1f859dc494a27e385fb8eb971f88098362c8f7da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/pr-only/includes/skip-level.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/pronly-on-skipLevel-suggestion/E2E_DocsBranch_Dynamic/pr-only/includes/skip-level.md) | :bulb:Suggestion | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/pr-only/[pr-only%202]%20unchanged%20file%20with%20more%20log?branch=pr-en-us-7248) | [Details](#user-content-d67623ed-ab660770)

<a id="d67623ed-ab660770"></a>
### [E2E_DocsBranch_Dynamic/pr-only/includes/skip-level.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/pronly-on-skipLevel-suggestion/E2E_DocsBranch_Dynamic/pr-only/includes/skip-level.md)
 - **Line 2, Column 1**: **[Suggestion-heading-skipped]** `````Skipped heading: H3 'heading'(pr-only/[pr-only 2] Unchanged file with more log.md(17,1) -> pr-only/includes/skip-level.md) followed by heading: H6 'skip level'(pr-only/[pr-only 2] Unchanged file with more log.md(17,1) -> pr-only/includes/skip-level.md(2,1)). Headings must increment with no skipped levels`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C7%5C24%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202007240634534210-7248%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LHfZsnlHmMaABIw68jWTWVHVWVGm%2BCNpvYB6AVzPUro%3D&st=2020-07-24T06%3A30%3A23Z&se=2020-08-24T06%3A35%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://opportal-sandbox.azurewebsites.net/#/repos/8b165afe-a866-8c48-e5c3-ead94440f27e?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[fe29655](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/fe29655f97fbcaecf9fee9d83f864e98dec5a0d1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/pr-only/includes/skip-level.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/pronly-on-skipLevel-suggestion/E2E_DocsBranch_Dynamic/pr-only/includes/skip-level.md) | :bulb:Suggestion | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/pr-only/[pr-only%202]%20unchanged%20file%20with%20more%20log?branch=pr-en-us-7248) | [Details](#user-content-d67623ed-dfc067ef)
[E2E_DocsBranch_Dynamic/pr-only/includes/unchanged-log-file.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/pronly-on-skipLevel-suggestion/E2E_DocsBranch_Dynamic/pr-only/includes/unchanged-log-file.md) | :bulb:Suggestion | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/pr-only/[pr-only%208]%20inclusion%20file%20with%20same%20logs?branch=pr-en-us-7248) | [Details](#user-content-04df9e9e-dfc067ef)

<a id="d67623ed-dfc067ef"></a>
### [E2E_DocsBranch_Dynamic/pr-only/includes/skip-level.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/pronly-on-skipLevel-suggestion/E2E_DocsBranch_Dynamic/pr-only/includes/skip-level.md)
 - **Line 2, Column 1**: **[Suggestion-heading-skipped]** `````Skipped heading: H3 'heading'(pr-only/[pr-only 2] Unchanged file with more log.md(17,1) -> pr-only/includes/skip-level.md) followed by heading: H6 'skip level'(pr-only/[pr-only 2] Unchanged file with more log.md(17,1) -> pr-only/includes/skip-level.md(2,1)). Headings must increment with no skipped levels`````

<a id="04df9e9e-dfc067ef"></a>
### [E2E_DocsBranch_Dynamic/pr-only/includes/unchanged-log-file.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/pronly-on-skipLevel-suggestion/E2E_DocsBranch_Dynamic/pr-only/includes/unchanged-log-file.md)
 - **Line 7, Column 1**: **[Suggestion-heading-no-content]** `````H4 'skip level'(pr-only/[pr-only 8] Inclusion file with same logs.md(8,1) -> pr-only/includes/unchanged-log-file.md(7,1)) contains no content. Add content or remove the unused heading.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C7%5C24%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202007240655332791-7248%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2B4UPwXKqg7bCzIdbUDy64AcvykD5OEiWUTqYxUH9XDM%3D&st=2020-07-24T06%3A57%3A02Z&se=2020-08-24T07%3A02%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://opportal-sandbox.azurewebsites.net/#/repos/8b165afe-a866-8c48-e5c3-ead94440f27e?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[71614f2](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/71614f2675b1842c440f1d5bde6ec6feb497a635)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/pr-only/includes/unchanged-log-file.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/pronly-on-skipLevel-suggestion/E2E_DocsBranch_Dynamic/pr-only/includes/unchanged-log-file.md) | :bulb:Suggestion | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/pr-only/[pr-only%208]%20inclusion%20file%20with%20same%20logs?branch=pr-en-us-7248) | [Details](#user-content-04df9e9e-c5d07893)
[E2E_DocsBranch_Dynamic/pr-only/includes/skip-level.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/pronly-on-skipLevel-suggestion/E2E_DocsBranch_Dynamic/pr-only/includes/skip-level.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/pr-only/[pr-only%202]%20unchanged%20file%20with%20more%20log?branch=pr-en-us-7248) |

<a id="04df9e9e-c5d07893"></a>
### [E2E_DocsBranch_Dynamic/pr-only/includes/unchanged-log-file.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/pronly-on-skipLevel-suggestion/E2E_DocsBranch_Dynamic/pr-only/includes/unchanged-log-file.md)
 - **Line 7, Column 1**: **[Suggestion-heading-no-content]** `````H4 'skip level'(pr-only/[pr-only 8] Inclusion file with same logs.md(8,1) -> pr-only/includes/unchanged-log-file.md(7,1)) contains no content. Add content or remove the unused heading.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C7%5C24%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202007240746284588-7248%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OWaU2%2FmwTQDL3pbtTpE3nEiWrzfTmt0Zc7sR%2BEsWLQM%3D&st=2020-07-24T07%3A42%3A02Z&se=2020-08-24T07%3A47%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://opportal-sandbox.azurewebsites.net/#/repos/8b165afe-a866-8c48-e5c3-ead94440f27e?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[5858388](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/58583885f5cd621bee2f74bc4eb9fd1ce06e84bc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/pr-only/includes/skip-level.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/pronly-on-skipLevel-suggestion/E2E_DocsBranch_Dynamic/pr-only/includes/skip-level.md) | :bulb:Suggestion | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/pr-only/[pr-only%202]%20unchanged%20file%20with%20more%20log?branch=pr-en-us-7248) | [Details](#user-content-d67623ed-f29b4a79)
[E2E_DocsBranch_Dynamic/pr-only/includes/unchanged-log-file.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/pronly-on-skipLevel-suggestion/E2E_DocsBranch_Dynamic/pr-only/includes/unchanged-log-file.md) | :bulb:Suggestion | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/pr-only/[pr-only%208]%20inclusion%20file%20with%20same%20logs?branch=pr-en-us-7248) | [Details](#user-content-04df9e9e-f29b4a79)

<a id="d67623ed-f29b4a79"></a>
### [E2E_DocsBranch_Dynamic/pr-only/includes/skip-level.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/pronly-on-skipLevel-suggestion/E2E_DocsBranch_Dynamic/pr-only/includes/skip-level.md)
 - **Line 2, Column 1**: **[Suggestion-heading-skipped]** `````Skipped heading: H3 'skip level'(pr-only/[pr-only 2] Unchanged file with more log.md(17,1) -> pr-only/includes/skip-level.md) followed by heading: H5 'skip level'(pr-only/[pr-only 2] Unchanged file with more log.md(17,1) -> pr-only/includes/skip-level.md(2,1)). Headings must increment with no skipped levels`````

<a id="04df9e9e-f29b4a79"></a>
### [E2E_DocsBranch_Dynamic/pr-only/includes/unchanged-log-file.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/pronly-on-skipLevel-suggestion/E2E_DocsBranch_Dynamic/pr-only/includes/unchanged-log-file.md)
 - **Line 7, Column 1**: **[Suggestion-heading-no-content]** `````H4 'skip level'(pr-only/[pr-only 8] Inclusion file with same logs.md(8,1) -> pr-only/includes/unchanged-log-file.md(7,1)) contains no content. Add content or remove the unused heading.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C7%5C24%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202007240800450868-7248%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AOrxrSPzKdWiBwiWGlVOiwTxxAdrWlNNzRetbbWxM18%3D&st=2020-07-24T07%3A56%3A18Z&se=2020-08-24T08%3A01%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://opportal-sandbox.azurewebsites.net/#/repos/8b165afe-a866-8c48-e5c3-ead94440f27e?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request closed without merging**
