### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[9885b43](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9885b43a669e7a422ac92a08706864f5004e6f65)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[9885b43](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9885b43a669e7a422ac92a08706864f5004e6f65)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2987) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C2%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001021225088906-2987%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JuDUzyvy82E5j5NhRBNKgG6X%2F0R28hv0ebmRd0bInlE%3D&st=2020-01-02T12%3A21%3A04Z&se=2020-02-02T12%3A26%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[9c68330](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9c68330b565ccc3317b5e12b7e97918ef0d18632)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[9c68330](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9c68330b565ccc3317b5e12b7e97918ef0d18632)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C2%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001021226131854-2987%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yM1EnOTtJVn5BB%2B4frPBiB2VtTo7xd13zK2WnhbH3ow%3D&st=2020-01-02T12%3A22%3A00Z&se=2020-02-02T12%3A27%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
