### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[9d01f71](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9d01f717fcd51bc1d373673704373081ad9dc67c)_: 

:clock10: **Pending**: waiting for processors ([10](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[9d01f71](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9d01f717fcd51bc1d373673704373081ad9dc67c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2329) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C27%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201911271103249750-2329%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9fpalIYKv3BOJMFiwpWcCoLTBIi5NZJ7UyagqxByeno%3D&st=2019-11-27T10%3A59%3A07Z&se=2019-12-28T11%3A04%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[da71ef2](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/da71ef276db718a4d66a917a0cddad6fce768847)_: 

:clock10: **Pending**: waiting for processors ([6](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[da71ef2](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/da71ef276db718a4d66a917a0cddad6fce768847)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C27%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201911271104369698-2329%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qS2onuenCaiPGYliyzpN0gkP%2FFt5ZW7YFlvXrLSBCJc%3D&st=2019-11-27T11%3A00%3A15Z&se=2019-12-28T11%3A05%3A15Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
