### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[fa895d5](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/fa895d5d0a053773afe3c17385da7d3a70010fc5)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[fa895d5](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/fa895d5d0a053773afe3c17385da7d3a70010fc5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-5361) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C29%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004291104246863-5361%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GA2aXxSDo407X0ye2W9SVSwS9zijRUF9h7bvdqSy8ok%3D&st=2020-04-29T11%3A00%3A43Z&se=2020-05-30T11%3A05%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[beab25e](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/beab25ea594d9604a8ca9466d3f07e96e9d520d8)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[beab25e](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/beab25ea594d9604a8ca9466d3f07e96e9d520d8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C29%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004291106285652-5361%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5zth71ClEDXBqWzxt6gIb8HLPeoIFdelOObsYIXW8Ec%3D&st=2020-04-29T11%3A02%3A16Z&se=2020-05-30T11%3A07%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
