### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[4549013](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/454901367aea562c351767f7380dd5c10b0fc271)_: 

:clock10: **Pending**: waiting for processors ([14](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 14 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[4549013](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/454901367aea562c351767f7380dd5c10b0fc271)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-5280) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C26%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004261104105265-5280%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pJuMt%2BYrpgTJuWxuk7W%2B72kSCtbVLa2ZpPspOZK1Na8%3D&st=2020-04-26T11%3A00%3A13Z&se=2020-05-27T11%3A05%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[41eefbe](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/41eefbe9ad9730c7f8a98914339ed81ffd7eed6d)_: 

:clock10: **Pending**: waiting for processors ([5](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[41eefbe](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/41eefbe9ad9730c7f8a98914339ed81ffd7eed6d)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C26%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004261106158842-5280%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Q%2FDuSqXlgK%2FbBfpXUlY56pu3xIEUHvsPcqY8fimf%2BnQ%3D&st=2020-04-26T11%3A01%3A50Z&se=2020-05-27T11%3A06%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
