### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[d8b2e95](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/d8b2e95010c187f891eaafa6f6709158a83b6dca)_: 

:clock10: **Pending**: waiting for processors ([13](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 13 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[d8b2e95](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/d8b2e95010c187f891eaafa6f6709158a83b6dca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2963) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C2%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001021104367994-2963%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qdp1IhJG7QUQuQUhxesGleg5DsRPXxeNdszf4rsIOuo%3D&st=2020-01-02T11%3A00%3A22Z&se=2020-02-02T11%3A05%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[801c4e4](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/801c4e4946a289e8d2b79120cfd28fdf9a834fa1)_: 

:clock10: **Pending**: waiting for processors ([13](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 13 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[801c4e4](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/801c4e4946a289e8d2b79120cfd28fdf9a834fa1)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C2%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001021105394040-2963%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=obWJo6rP1OV%2FBwN1i4lPksFAg99KB2cwJgiYQFaCq6c%3D&st=2020-01-02T11%3A01%3A21Z&se=2020-02-02T11%3A06%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
