### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[bf3d2f7](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/bf3d2f7a74be801d346fda89be8577301b7dbc07)_: 

:clock10: **Pending**: waiting for processors ([13](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 13 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[bf3d2f7](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/bf3d2f7a74be801d346fda89be8577301b7dbc07)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-3117) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C9%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001090146055171-3117%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kRYMShXsLXIUE2DDk1EogrXuv2jMwIAaw68KaGqwe9Q%3D&st=2020-01-09T01%3A42%3A02Z&se=2020-02-09T01%3A47%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[a771129](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/a7711294dcaf1839a1b48d4e83dab1dd847dd06f)_: 

:clock10: **Pending**: waiting for processors ([8](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[a771129](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/a7711294dcaf1839a1b48d4e83dab1dd847dd06f)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C9%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001090146592399-3117%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DyDs5bstDSg90mlxDPkdSKG70N%2BXPDyziswR7N1hMpg%3D&st=2020-01-09T01%3A42%3A46Z&se=2020-02-09T01%3A47%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
