### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[c8d7699](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/c8d7699c32f6451e0fe9a0119132fb8588e51879)_: 

:clock10: **Pending**: waiting for processors ([8](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[c8d7699](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/c8d7699c32f6451e0fe9a0119132fb8588e51879)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :bulb:Suggestion | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-1114) | [Details](#user-content-b441094d-95435337)

<a id="b441094d-95435337"></a>
### [E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md)
 - **Line 0**: **[Suggestion]** `````Missing required attribute: 'author'. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````
 - **Line 0**: **[Suggestion]** `````Missing required attribute: 'title'. Add a title string to show in search engine results. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C8%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201909081802314254-1114%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VnnXhjT%2Bk%2FYzPA7lcLQuyNwtYO4F%2FNWK%2Fb4FIpZT27s%3D&st=2019-09-08T17%3A58%3A19Z&se=2019-10-09T18%3A03%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[136a380](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/136a380b7f4f2b9b4f764fc0a9edde9306ca1c1b)_: 

:clock10: **Pending**: waiting for processors ([8](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[136a380](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/136a380b7f4f2b9b4f764fc0a9edde9306ca1c1b)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C8%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201909081803431444-1114%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RgGqXfgTkST6DC76dEjFNrRNlvyX1ELP1QYM3Ozgegs%3D&st=2019-09-08T17%3A59%3A28Z&se=2019-10-09T18%3A04%3A28Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
