### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[75b79e6](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/75b79e6ca16bc5715b8b26e1a394d97356c3c77d)_: 

:clock10: **Pending**: waiting for processors ([8](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[75b79e6](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/75b79e6ca16bc5715b8b26e1a394d97356c3c77d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-4886) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C7%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004070059134290-4886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CUBwdBDYpYNmhSXeT7nPP3uJtTIMafymajYflBHkzhY%3D&st=2020-04-07T00%3A54%3A45Z&se=2020-05-08T00%3A59%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[712c8f3](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/712c8f3a13629736c5f23bafd710c476b49a2070)_: 

:clock10: **Pending**: waiting for processors ([8](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[712c8f3](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/712c8f3a13629736c5f23bafd710c476b49a2070)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C7%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004070100176293-4886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=82xLE6qq24KKt2xushgx5x%2F7sGMzMsYY9PNzfNUnIag%3D&st=2020-04-07T00%3A55%3A51Z&se=2020-05-08T01%3A00%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
