### PR TITLE
Incremental PR: add a resource and delete the added resource

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[d461e32](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/d461e32560b77f294c3872b8c100243203cbea0b)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[d461e32](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/d461e32560b77f294c3872b8c100243203cbea0b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/incrementalPR-addresource.jpg](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addresource/E2E_DocsBranch_Dynamic/incrementalPR-addresource.jpg) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/incrementalpr-addresource.jpg?branch=pr-en-us-5438) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C5%5C6%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202005061131093481-5438%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=k96j7Pdk8cfxYO6NCnOCeox%2Btw2YcC8tVpCem6%2F5xHE%3D&st=2020-05-06T11%3A26%3A52Z&se=2020-06-06T11%3A31%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[048b14a](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/048b14a1e02f915e5929111f1b7e38e33bd2325a)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[048b14a](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/048b14a1e02f915e5929111f1b7e38e33bd2325a)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C5%5C6%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202005061132136556-5438%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gwkPb4Bl7f6waJP4HcjvT83PAAYFyrO0Nnk9XZuuhEQ%3D&st=2020-05-06T11%3A28%3A25Z&se=2020-06-06T11%3A33%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
