### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[899d40c](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/899d40cb9b1b73b49d6021cca3bee4db534727bf)_: 

:clock10: **Pending**: waiting for processors ([14](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 14 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[899d40c](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/899d40cb9b1b73b49d6021cca3bee4db534727bf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-4247) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C10%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003100846017584-4247%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zm6dq8Rn%2BHnXKA2L3l1DHzzHz3iF4cfQXnidHudlX6U%3D&st=2020-03-10T08%3A41%3A40Z&se=2020-04-10T08%3A46%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[92b47f5](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/92b47f58639a735226ed3a2314ef9b7016972ad8)_: 

:clock10: **Pending**: waiting for processors ([9](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[92b47f5](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/92b47f58639a735226ed3a2314ef9b7016972ad8)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C10%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003100847006476-4247%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=T6RQTtvA4HMf2c%2BFelDbj7oXJ4dRPT0u6GvXodg9cPk%3D&st=2020-03-10T08%3A42%3A48Z&se=2020-04-10T08%3A47%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
