### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[bd19e03](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/bd19e03cf2e9197b4da9c9e15fc11b726875775a)_: 

:clock10: **Pending**: waiting for processors ([14](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 14 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[bd19e03](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/bd19e03cf2e9197b4da9c9e15fc11b726875775a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-4318) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C11%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003111103082237-4318%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=22fasR7CYkANsw%2FZC6x8712uiOF8yToGlX5HbjBD%2FEk%3D&st=2020-03-11T10%3A58%3A47Z&se=2020-04-11T11%3A03%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[dd59752](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/dd59752a2c548ca3f3ed70b223541c9e4019bedf)_: 

:clock10: **Pending**: waiting for processors ([14](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 14 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[dd59752](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/dd59752a2c548ca3f3ed70b223541c9e4019bedf)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C11%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003111104130270-4318%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=N64yOrIx%2F3zmM3oJqAnEFtgsIC46XR7HP%2FE9167spmg%3D&st=2020-03-11T10%3A59%3A56Z&se=2020-04-11T11%3A04%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
