### PR TITLE
Update configure-aad.md

### PR DESCRIPTION
**Pull request by fkpwolf**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[75bee5d](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/75bee5d1c59229e70bb2063c17fb24d96e42a7e9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/service/configure-aad.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/configure-aad.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/service/configure-aad?branch=pr-en-us-9741) | [Details](#user-content-5fb622fe-b6c3c41e)
[E2E_DocsBranch_Dynamic/service/connect-metamask.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/connect-metamask.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/service/connect-metamask?branch=pr-en-us-9741) | [Details](#user-content-14440b9c-b6c3c41e)
[E2E_DocsBranch_Dynamic/service/send-transaction.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/send-transaction.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/service/send-transaction?branch=pr-en-us-9741) | [Details](#user-content-05842f66-b6c3c41e)
[E2E_DocsBranch_Dynamic/service/overview.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/overview.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/service/overview?branch=pr-en-us-9741) | [Details](#user-content-5e6e3e47-b6c3c41e)
[E2E_DocsBranch_Dynamic/service/configure-transaction-nodes.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/configure-transaction-nodes.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/service/configure-transaction-nodes?branch=pr-en-us-9741) | [Details](#user-content-cf66f07f-b6c3c41e)
[E2E_DocsBranch_Dynamic/service/manage-consortium-powershell.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/manage-consortium-powershell.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/service/manage-consortium-powershell?branch=pr-en-us-9741) | [Details](#user-content-8148b71f-b6c3c41e)
[E2E_DocsBranch_Dynamic/service/data-manager-cli.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/data-manager-cli.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/service/data-manager-cli?branch=pr-en-us-9741) | [Details](#user-content-35e9353e-b6c3c41e)
[E2E_DocsBranch_Dynamic/service/data-manager-cosmosdb.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/data-manager-cosmosdb.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/service/data-manager-cosmosdb?branch=pr-en-us-9741) | [Details](#user-content-f0bac300-b6c3c41e)
[E2E_DocsBranch_Dynamic/service/ledger-versions.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/ledger-versions.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/service/ledger-versions?branch=pr-en-us-9741) | [Details](#user-content-86ed040f-b6c3c41e)
[E2E_DocsBranch_Dynamic/service/data-security.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/data-security.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/service/data-security?branch=pr-en-us-9741) | [Details](#user-content-507a490c-b6c3c41e)
[E2E_DocsBranch_Dynamic/service/data-manager.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/data-manager.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/service/data-manager?branch=pr-en-us-9741) | [Details](#user-content-9adbb7b0-b6c3c41e)
[E2E_DocsBranch_Dynamic/service/monitor-azure-blockchain-service.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/monitor-azure-blockchain-service.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/service/monitor-azure-blockchain-service?branch=pr-en-us-9741) | [Details](#user-content-42d24ed6-b6c3c41e)
[E2E_DocsBranch_Dynamic/service/data-manager-portal.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/data-manager-portal.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/service/data-manager-portal?branch=pr-en-us-9741) | [Details](#user-content-839827b5-b6c3c41e)
[E2E_DocsBranch_Dynamic/service/create-member-template.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/create-member-template.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/service/create-member-template?branch=pr-en-us-9741) | [Details](#user-content-6073e591-b6c3c41e)
[E2E_DocsBranch_Dynamic/service/consortium.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/consortium.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/service/consortium?branch=pr-en-us-9741) | [Details](#user-content-083d8639-b6c3c41e)
[E2E_DocsBranch_Dynamic/service/manage-cli.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/manage-cli.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/service/manage-cli?branch=pr-en-us-9741) | [Details](#user-content-b39ce45b-b6c3c41e)
[E2E_DocsBranch_Dynamic/service/connect-geth.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/connect-geth.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/service/connect-geth?branch=pr-en-us-9741) | [Details](#user-content-ff21b723-b6c3c41e)
[E2E_DocsBranch_Dynamic/service/limits.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/limits.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/service/limits?branch=pr-en-us-9741) | [Details](#user-content-6866b2c2-b6c3c41e)
[E2E_DocsBranch_Dynamic/service/create-member.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/create-member.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/service/create-member?branch=pr-en-us-9741) | [Details](#user-content-b10df5c3-b6c3c41e)
[E2E_DocsBranch_Dynamic/service/ethereum-logic-app.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/ethereum-logic-app.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/service/ethereum-logic-app?branch=pr-en-us-9741) | [Details](#user-content-a4f875b7-b6c3c41e)
[E2E_DocsBranch_Dynamic/service/whats-new.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/whats-new.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/service/whats-new?branch=pr-en-us-9741) | [Details](#user-content-18e87f6e-b6c3c41e)
[E2E_DocsBranch_Dynamic/service/develop.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/develop.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/service/develop?branch=pr-en-us-9741) | [Details](#user-content-e188685c-b6c3c41e)
[E2E_DocsBranch_Dynamic/service/connect-vscode.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/connect-vscode.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/service/connect-vscode?branch=pr-en-us-9741) | [Details](#user-content-c5d53d3b-b6c3c41e)
[E2E_DocsBranch_Dynamic/service/create-member-cli.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/create-member-cli.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/service/create-member-cli?branch=pr-en-us-9741) | [Details](#user-content-75b1f7df-b6c3c41e)

<a id="5fb622fe-b6c3c41e"></a>
### [E2E_DocsBranch_Dynamic/service/configure-aad.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/configure-aad.md)
 - **Line 3, Column 14**: **[Warning-description-bad-length]** `````String 'description' is too short: 76 characters. Length should be >= 500. too short...v2`````
 - **Line 2, Column 1**: **[Suggestion-title-suffix-missing]** `````Missing required attribute: 'titleSuffix'. Missing attribute: titleSuffix. Add a titleSuffix value to append branding information to your titles.`````

<a id="14440b9c-b6c3c41e"></a>
### [E2E_DocsBranch_Dynamic/service/connect-metamask.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/connect-metamask.md)
 - **Line 3, Column 14**: **[Warning-description-bad-length]** `````String 'description' is too short: 90 characters. Length should be >= 500. too short...v2`````
 - **Line 2, Column 1**: **[Suggestion-title-suffix-missing]** `````Missing required attribute: 'titleSuffix'. Missing attribute: titleSuffix. Add a titleSuffix value to append branding information to your titles.`````

<a id="05842f66-b6c3c41e"></a>
### [E2E_DocsBranch_Dynamic/service/send-transaction.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/send-transaction.md)
 - **Line 3, Column 14**: **[Warning-description-bad-length]** `````String 'description' is too short: 179 characters. Length should be >= 500. too short...v2`````
 - **Line 2, Column 1**: **[Suggestion-title-suffix-missing]** `````Missing required attribute: 'titleSuffix'. Missing attribute: titleSuffix. Add a titleSuffix value to append branding information to your titles.`````

<a id="5e6e3e47-b6c3c41e"></a>
### [E2E_DocsBranch_Dynamic/service/overview.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/overview.md)
 - **Line 3, Column 14**: **[Warning-description-bad-length]** `````String 'description' is too short: 36 characters. Length should be >= 500. too short...v2`````
 - **Line 2, Column 1**: **[Suggestion-title-suffix-missing]** `````Missing required attribute: 'titleSuffix'. Missing attribute: titleSuffix. Add a titleSuffix value to append branding information to your titles.`````

<a id="cf66f07f-b6c3c41e"></a>
### [E2E_DocsBranch_Dynamic/service/configure-transaction-nodes.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/configure-transaction-nodes.md)
 - **Line 3, Column 14**: **[Warning-description-bad-length]** `````String 'description' is too short: 59 characters. Length should be >= 500. too short...v2`````
 - **Line 2, Column 1**: **[Suggestion-title-suffix-missing]** `````Missing required attribute: 'titleSuffix'. Missing attribute: titleSuffix. Add a titleSuffix value to append branding information to your titles.`````

<a id="8148b71f-b6c3c41e"></a>
### [E2E_DocsBranch_Dynamic/service/manage-consortium-powershell.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/manage-consortium-powershell.md)
 - **Line 3, Column 14**: **[Warning-description-bad-length]** `````String 'description' is too short: 90 characters. Length should be >= 500. too short...v2`````
 - **Line 2, Column 1**: **[Suggestion-title-suffix-missing]** `````Missing required attribute: 'titleSuffix'. Missing attribute: titleSuffix. Add a titleSuffix value to append branding information to your titles.`````

<a id="35e9353e-b6c3c41e"></a>
### [E2E_DocsBranch_Dynamic/service/data-manager-cli.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/data-manager-cli.md)
 - **Line 3, Column 14**: **[Warning-description-bad-length]** `````String 'description' is too short: 88 characters. Length should be >= 500. too short...v2`````
 - **Line 2, Column 1**: **[Suggestion-title-suffix-missing]** `````Missing required attribute: 'titleSuffix'. Missing attribute: titleSuffix. Add a titleSuffix value to append branding information to your titles.`````

<a id="f0bac300-b6c3c41e"></a>
### [E2E_DocsBranch_Dynamic/service/data-manager-cosmosdb.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/data-manager-cosmosdb.md)
 - **Line 3, Column 14**: **[Warning-description-bad-length]** `````String 'description' is too short: 99 characters. Length should be >= 500. too short...v2`````
 - **Line 2, Column 1**: **[Suggestion-title-suffix-missing]** `````Missing required attribute: 'titleSuffix'. Missing attribute: titleSuffix. Add a titleSuffix value to append branding information to your titles.`````

<a id="86ed040f-b6c3c41e"></a>
### [E2E_DocsBranch_Dynamic/service/ledger-versions.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/ledger-versions.md)
 - **Line 3, Column 14**: **[Warning-description-bad-length]** `````String 'description' is too short: 125 characters. Length should be >= 500. too short...v2`````
 - **Line 2, Column 1**: **[Suggestion-title-suffix-missing]** `````Missing required attribute: 'titleSuffix'. Missing attribute: titleSuffix. Add a titleSuffix value to append branding information to your titles.`````

<a id="507a490c-b6c3c41e"></a>
### [E2E_DocsBranch_Dynamic/service/data-security.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/data-security.md)
 - **Line 3, Column 14**: **[Warning-description-bad-length]** `````String 'description' is too short: 58 characters. Length should be >= 500. too short...v2`````
 - **Line 2, Column 1**: **[Suggestion-title-suffix-missing]** `````Missing required attribute: 'titleSuffix'. Missing attribute: titleSuffix. Add a titleSuffix value to append branding information to your titles.`````

<a id="9adbb7b0-b6c3c41e"></a>
### [E2E_DocsBranch_Dynamic/service/data-manager.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/data-manager.md)
 - **Line 3, Column 14**: **[Warning-description-bad-length]** `````String 'description' is too short: 99 characters. Length should be >= 500. too short...v2`````
 - **Line 2, Column 1**: **[Suggestion-title-suffix-missing]** `````Missing required attribute: 'titleSuffix'. Missing attribute: titleSuffix. Add a titleSuffix value to append branding information to your titles.`````

<a id="42d24ed6-b6c3c41e"></a>
### [E2E_DocsBranch_Dynamic/service/monitor-azure-blockchain-service.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/monitor-azure-blockchain-service.md)
 - **Line 3, Column 14**: **[Warning-description-bad-length]** `````String 'description' is too short: 57 characters. Length should be >= 500. too short...v2`````
 - **Line 2, Column 1**: **[Suggestion-title-suffix-missing]** `````Missing required attribute: 'titleSuffix'. Missing attribute: titleSuffix. Add a titleSuffix value to append branding information to your titles.`````

<a id="839827b5-b6c3c41e"></a>
### [E2E_DocsBranch_Dynamic/service/data-manager-portal.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/data-manager-portal.md)
 - **Line 3, Column 14**: **[Warning-description-bad-length]** `````String 'description' is too short: 94 characters. Length should be >= 500. too short...v2`````
 - **Line 2, Column 1**: **[Suggestion-title-suffix-missing]** `````Missing required attribute: 'titleSuffix'. Missing attribute: titleSuffix. Add a titleSuffix value to append branding information to your titles.`````

<a id="6073e591-b6c3c41e"></a>
### [E2E_DocsBranch_Dynamic/service/create-member-template.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/create-member-template.md)
 - **Line 3, Column 14**: **[Warning-description-bad-length]** `````String 'description' is too short: 96 characters. Length should be >= 500. too short...v2`````
 - **Line 2, Column 1**: **[Suggestion-title-suffix-missing]** `````Missing required attribute: 'titleSuffix'. Missing attribute: titleSuffix. Add a titleSuffix value to append branding information to your titles.`````

<a id="083d8639-b6c3c41e"></a>
### [E2E_DocsBranch_Dynamic/service/consortium.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/consortium.md)
 - **Line 3, Column 14**: **[Warning-description-bad-length]** `````String 'description' is too short: 83 characters. Length should be >= 500. too short...v2`````
 - **Line 2, Column 1**: **[Suggestion-title-suffix-missing]** `````Missing required attribute: 'titleSuffix'. Missing attribute: titleSuffix. Add a titleSuffix value to append branding information to your titles.`````

<a id="b39ce45b-b6c3c41e"></a>
### [E2E_DocsBranch_Dynamic/service/manage-cli.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/manage-cli.md)
 - **Line 3, Column 14**: **[Warning-description-bad-length]** `````String 'description' is too short: 53 characters. Length should be >= 500. too short...v2`````
 - **Line 2, Column 1**: **[Suggestion-title-suffix-missing]** `````Missing required attribute: 'titleSuffix'. Missing attribute: titleSuffix. Add a titleSuffix value to append branding information to your titles.`````

<a id="ff21b723-b6c3c41e"></a>
### [E2E_DocsBranch_Dynamic/service/connect-geth.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/connect-geth.md)
 - **Line 3, Column 14**: **[Warning-description-bad-length]** `````String 'description' is too short: 70 characters. Length should be >= 500. too short...v2`````
 - **Line 2, Column 1**: **[Suggestion-title-suffix-missing]** `````Missing required attribute: 'titleSuffix'. Missing attribute: titleSuffix. Add a titleSuffix value to append branding information to your titles.`````

<a id="6866b2c2-b6c3c41e"></a>
### [E2E_DocsBranch_Dynamic/service/limits.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/limits.md)
 - **Line 3, Column 14**: **[Warning-description-bad-length]** `````String 'description' is too short: 73 characters. Length should be >= 500. too short...v2`````
 - **Line 2, Column 1**: **[Suggestion-title-suffix-missing]** `````Missing required attribute: 'titleSuffix'. Missing attribute: titleSuffix. Add a titleSuffix value to append branding information to your titles.`````

<a id="b10df5c3-b6c3c41e"></a>
### [E2E_DocsBranch_Dynamic/service/create-member.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/create-member.md)
 - **Line 3, Column 14**: **[Warning-description-bad-length]** `````String 'description' is too short: 93 characters. Length should be >= 500. too short...v2`````
 - **Line 2, Column 1**: **[Suggestion-title-suffix-missing]** `````Missing required attribute: 'titleSuffix'. Missing attribute: titleSuffix. Add a titleSuffix value to append branding information to your titles.`````

<a id="a4f875b7-b6c3c41e"></a>
### [E2E_DocsBranch_Dynamic/service/ethereum-logic-app.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/ethereum-logic-app.md)
 - **Line 3, Column 14**: **[Warning-description-bad-length]** `````String 'description' is too short: 133 characters. Length should be >= 500. too short...v2`````
 - **Line 2, Column 1**: **[Suggestion-title-suffix-missing]** `````Missing required attribute: 'titleSuffix'. Missing attribute: titleSuffix. Add a titleSuffix value to append branding information to your titles.`````

<a id="18e87f6e-b6c3c41e"></a>
### [E2E_DocsBranch_Dynamic/service/whats-new.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/whats-new.md)
 - **Line 3, Column 14**: **[Warning-description-bad-length]** `````String 'description' is too short: 128 characters. Length should be >= 500. too short...v2`````
 - **Line 2, Column 1**: **[Suggestion-title-suffix-missing]** `````Missing required attribute: 'titleSuffix'. Missing attribute: titleSuffix. Add a titleSuffix value to append branding information to your titles.`````

<a id="e188685c-b6c3c41e"></a>
### [E2E_DocsBranch_Dynamic/service/develop.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/develop.md)
 - **Line 3, Column 14**: **[Warning-description-bad-length]** `````String 'description' is too short: 65 characters. Length should be >= 500. too short...v2`````
 - **Line 2, Column 1**: **[Suggestion-title-suffix-missing]** `````Missing required attribute: 'titleSuffix'. Missing attribute: titleSuffix. Add a titleSuffix value to append branding information to your titles.`````

<a id="c5d53d3b-b6c3c41e"></a>
### [E2E_DocsBranch_Dynamic/service/connect-vscode.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/connect-vscode.md)
 - **Line 3, Column 14**: **[Warning-description-bad-length]** `````String 'description' is too short: 145 characters. Length should be >= 500. too short...v2`````
 - **Line 2, Column 1**: **[Suggestion-title-suffix-missing]** `````Missing required attribute: 'titleSuffix'. Missing attribute: titleSuffix. Add a titleSuffix value to append branding information to your titles.`````

<a id="75b1f7df-b6c3c41e"></a>
### [E2E_DocsBranch_Dynamic/service/create-member-cli.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/create-member-cli.md)
 - **Line 3, Column 14**: **[Warning-description-bad-length]** `````String 'description' is too short: 90 characters. Length should be >= 500. too short...v2`````
 - **Line 2, Column 1**: **[Suggestion-title-suffix-missing]** `````Missing required attribute: 'titleSuffix'. Missing attribute: titleSuffix. Add a titleSuffix value to append branding information to your titles.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C10%5C13%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202010130559460280-9741%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Mcra3xUaoghBIc7%2FY%2BF3au%2FIJ4ZELyZJbFOEcOklufo%3D&st=2020-10-13T05%3A55%3A19Z&se=2020-11-13T06%3A00%3A19Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://opportal-sandbox.azurewebsites.net/#/repos/8b165afe-a866-8c48-e5c3-ead94440f27e?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by fkpwolf** [comment]
too many error

**Comment by fkpwolf** [comment]
enabled pr only, retry

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[75bee5d](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/75bee5d1c59229e70bb2063c17fb24d96e42a7e9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/service/configure-aad.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/configure-aad.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/service/configure-aad?branch=pr-en-us-9741) | [Details](#user-content-5fb622fe-93cb724c)

<a id="5fb622fe-93cb724c"></a>
### [E2E_DocsBranch_Dynamic/service/configure-aad.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/fkpwolf-patch-2/E2E_DocsBranch_Dynamic/service/configure-aad.md)
 - **Line 3, Column 14**: **[Warning-description-bad-length]** `````String 'description' is too short: 76 characters. Length should be >= 500. too short...v2`````
 - **Line 2, Column 1**: **[Suggestion-title-suffix-missing]** `````Missing required attribute: 'titleSuffix'. Missing attribute: titleSuffix. Add a titleSuffix value to append branding information to your titles.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C10%5C13%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202010130605393720-9741%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=neP9Qn2T4W1E0C10CDC6z2U%2BLci%2FisezcYemWo%2BIJ1k%3D&st=2020-10-13T06%3A01%3A13Z&se=2020-11-13T06%3A06%3A13Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://opportal-sandbox.azurewebsites.net/#/repos/8b165afe-a866-8c48-e5c3-ead94440f27e?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request closed without merging**
