### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[9bc7ccc](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9bc7ccc42897bf145b5e52738517e4479e042625)_: 

:clock10: **Pending**: waiting for processors ([9](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[9bc7ccc](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9bc7ccc42897bf145b5e52738517e4479e042625)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-1345) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C30%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201909301103186455-1345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xBIYnfztuX9DVwGG1sJQX%2Bu03PnFCH5GpOOWmxDqi9k%3D&st=2019-09-30T10%3A58%3A56Z&se=2019-10-31T11%3A03%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[442e351](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/442e35114282f506d51023c4e24e3939370aa912)_: 

:clock10: **Pending**: waiting for processors ([9](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[442e351](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/442e35114282f506d51023c4e24e3939370aa912)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C30%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201909301104275786-1345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NOjEVXEwsVafxHB2xD4o4VRZmLEJ%2F5KlnuJRq9JQwYE%3D&st=2019-09-30T11%3A00%3A13Z&se=2019-10-31T11%3A05%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
