### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[233f133](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/233f133ad669a62c918a866383351521a4d1ebad)_: 

:clock10: **Pending**: waiting for processors ([10](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[233f133](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/233f133ad669a62c918a866383351521a4d1ebad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-4932) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C8%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004080841401063-4932%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zbwK6ep61Y%2Fc5rriChh4Fu%2BhOynaG%2FaqfKxiJCK1dtM%3D&st=2020-04-08T08%3A37%3A10Z&se=2020-05-09T08%3A42%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[381d586](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/381d5869924e83ebe539817501b6875e14fb89fb)_: 

:clock10: **Pending**: waiting for processors ([5](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[381d586](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/381d5869924e83ebe539817501b6875e14fb89fb)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C8%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004080842380545-4932%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZruZec9IB0684wOWd06be%2Bgd%2F4Yv7VIKS8%2Bq147kSpU%3D&st=2020-04-08T08%3A38%3A07Z&se=2020-05-09T08%3A43%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
