### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[1f9ae17](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/1f9ae1796857b14661cc02dc29112d81122f1a45)_: 

:clock10: **Pending**: waiting for processors ([13](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 13 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[1f9ae17](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/1f9ae1796857b14661cc02dc29112d81122f1a45)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-1812) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C30%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201910301102547585-1812%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=q6EB8rZlAgjbJwChZEUgxPVWYusas7Wbh3s7DQvgX2w%3D&st=2019-10-30T10%3A58%3A32Z&se=2019-11-30T11%3A03%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[025dfc1](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/025dfc1d394a60a4c37c7907ad90e78f322416f7)_: 

:clock10: **Pending**: waiting for processors ([13](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 13 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[025dfc1](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/025dfc1d394a60a4c37c7907ad90e78f322416f7)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C30%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201910301103575569-1812%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ny1CNV1skImT%2BqYKoxRrAUCet%2BqNW7Oua1n8CGQziCc%3D&st=2019-10-30T10%3A59%3A34Z&se=2019-11-30T11%3A04%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
