### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[71014c6](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/71014c6af18d204606f46a5e1d24bf58efd2ce50)_: 

:clock10: **Pending**: waiting for processors ([9](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[71014c6](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/71014c6af18d204606f46a5e1d24bf58efd2ce50)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-3377) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C23%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001231104154085-3377%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mNrNctXYQ%2F8%2BiW31BdVH7u4cZ%2F6eCyKxhAgIMw3OP%2BQ%3D&st=2020-01-23T11%3A00%3A16Z&se=2020-02-23T11%3A05%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[4413440](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/44134403008752fd5d6df91f666dec63a4c526e1)_: 

:clock10: **Pending**: waiting for processors ([17](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 17 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[4413440](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/44134403008752fd5d6df91f666dec63a4c526e1)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C23%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001231106199620-3377%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7yffu%2Fj1n4ErYajm6U8KzqJFefHAZm0qhBlq7gSDf24%3D&st=2020-01-23T11%3A02%3A02Z&se=2020-02-23T11%3A07%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
