### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[714179b](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/714179b738e131790cafc9d49c5cc3f0b7bfc126)_: 

:clock10: **Pending**: waiting for processors ([14](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 14 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[714179b](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/714179b738e131790cafc9d49c5cc3f0b7bfc126)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-5252) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C23%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004231107234975-5252%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QC6o6gak9wombbw%2FaSROaJLVW2rEYbRevg2CjWRfa9I%3D&st=2020-04-23T11%3A03%3A08Z&se=2020-05-24T11%3A08%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[f6c1e31](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/f6c1e3146857e86d00ccddbf757e929424c09b5d)_: 

:clock10: **Pending**: waiting for processors ([14](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 14 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[f6c1e31](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/f6c1e3146857e86d00ccddbf757e929424c09b5d)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C23%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004231108226440-5252%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0jS6jwQuv%2FYzwVFFRReFHtKDIrK7tXQN%2B4%2B7tXxZEAQ%3D&st=2020-04-23T11%3A04%3A00Z&se=2020-05-24T11%3A09%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
