### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[23c9da5](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/23c9da583b9f7dffacf05f9e43cd985cbfbdc628)_: 

:clock10: **Pending**: waiting for processors ([16](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 16 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[23c9da5](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/23c9da583b9f7dffacf05f9e43cd985cbfbdc628)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-1602) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C16%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201910161104072270-1602%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BRqgtBXyTJl6ywjnEzCE%2F6r%2BPjt53MB50iWB0d8RAzg%3D&st=2019-10-16T10%3A59%3A43Z&se=2019-11-16T11%3A04%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[fc80eae](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/fc80eae2e70d0ab96de9d5fcac4331a490dc70f0)_: 

:clock10: **Pending**: waiting for processors ([7](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 7 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[fc80eae](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/fc80eae2e70d0ab96de9d5fcac4331a490dc70f0)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C16%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201910161105044170-1602%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eHqpWGlWrqdbw%2BtsdOGeUcBlErjyetJNWOfMuv9qXuk%3D&st=2019-10-16T11%3A00%3A37Z&se=2019-11-16T11%3A05%3A37Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
