### PR TITLE
Incremental PR: add a resource and delete the added resource

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[edefe61](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/edefe61dca374f125831adbf2cd62c83eb204efa)_: 

:clock10: **Pending**: waiting for processors ([33](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 33 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[edefe61](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/edefe61dca374f125831adbf2cd62c83eb204efa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/incrementalPR-addresource.jpg](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addresource/E2E_DocsBranch_Dynamic/incrementalPR-addresource.jpg) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/incrementalpr-addresource.jpg?branch=pr-en-us-2201) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C20%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201911200356167378-2201%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5YjUFCrWQhhUaRs%2Fi8LAgEo%2F0OKA7SjJzO14UBrCvws%3D&st=2019-11-20T03%3A51%3A54Z&se=2019-12-21T03%3A56%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[a5e72ac](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/a5e72ac409696f1805b9f84f4b61fa63b8296a1c)_: 

:clock10: **Pending**: waiting for processors ([35](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 35 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[a5e72ac](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/a5e72ac409696f1805b9f84f4b61fa63b8296a1c)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C20%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201911200357221928-2201%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zYhzY2HuJsx6lVSdx5g9yGUHIj9fBuK%2FiBtE51UuYE8%3D&st=2019-11-20T03%3A53%3A00Z&se=2019-12-21T03%3A58%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
