### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[05ae3a1](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/05ae3a1500e5b9ad658bb2bd330e5f712c51f04d)_: 

:clock10: **Pending**: waiting for processors ([7](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 7 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[05ae3a1](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/05ae3a1500e5b9ad658bb2bd330e5f712c51f04d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-1534) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C13%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201910131105183109-1534%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GEMTzV56yyRMC%2BjRmeg46tqdTf5%2BpRKUc8kDqTPoyxQ%3D&st=2019-10-13T11%3A00%3A58Z&se=2019-11-13T11%3A05%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[2c6c6f5](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/2c6c6f5999db796eaa25c95734bd2530d43d987b)_: 

:clock10: **Pending**: waiting for processors ([7](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 7 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[2c6c6f5](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/2c6c6f5999db796eaa25c95734bd2530d43d987b)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C13%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201910131106147255-1534%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=f0WfM5ey3CIk%2BuMB3%2Fd36PHkYCAW%2Bx482ZGp0M0Dv1w%3D&st=2019-10-13T11%3A02%3A00Z&se=2019-11-13T11%3A07%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
