### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[918445d](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/918445dc034bfef5c4cccfae9a2a86b9dcb8f895)_: 

:clock10: **Pending**: waiting for processors ([8](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[918445d](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/918445dc034bfef5c4cccfae9a2a86b9dcb8f895)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2819) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C25%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912251104160313-2819%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KyApz3%2FdpbX6ryjsn6M%2FTXlNmjLgE5PUlLtQC3AjW30%3D&st=2019-12-25T10%3A59%3A59Z&se=2020-01-25T11%3A04%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[e5af262](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/e5af2629620038d1c4f326340f9be3c10f86bb4c)_: 

:clock10: **Pending**: waiting for processors ([9](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[e5af262](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/e5af2629620038d1c4f326340f9be3c10f86bb4c)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C25%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912251105211784-2819%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Kfyhq0257ZcxqpQBxwtky%2BLwRY9DU5XQ9w65cVhINTU%3D&st=2019-12-25T11%3A01%3A09Z&se=2020-01-25T11%3A06%3A09Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
