### PR TITLE
Incremental PR: add a resource and delete the added resource

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[1139fcc](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/1139fcca6ce3dd337a3d6bcd6512a493fa5d0a45)_: 

:clock10: **Pending**: waiting for processors ([5](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[1139fcc](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/1139fcca6ce3dd337a3d6bcd6512a493fa5d0a45)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/incrementalPR-addresource.jpg](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addresource/E2E_DocsBranch_Dynamic/incrementalPR-addresource.jpg) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/incrementalpr-addresource.jpg?branch=pr-en-us-5398) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C30%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004301128181489-5398%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=s4fWu2touqO6Yt8Zb6mYOsJSHnyrw%2FocSR4qwGak6U4%3D&st=2020-04-30T11%3A24%3A01Z&se=2020-05-31T11%3A29%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[c27690c](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/c27690c4fd79c07bcccce78aaa71cef9767a7d6a)_: 

:clock10: **Pending**: waiting for processors ([5](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[c27690c](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/c27690c4fd79c07bcccce78aaa71cef9767a7d6a)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C30%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004301129161331-5398%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zs0oR%2BKTCNIzRYQ8Pb1CQ7yD7WVvO6z3bXans7d4itw%3D&st=2020-04-30T11%3A24%3A58Z&se=2020-05-31T11%3A29%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
