### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[b6b7801](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/b6b7801280d89a08c72b19801ecd1d5e478e357a)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[b6b7801](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/b6b7801280d89a08c72b19801ecd1d5e478e357a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2184) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C20%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201911200340032580-2184%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=b5PgjOWngmHzob4VCLKLmY9LxTZ0TFJ1iqy5Y%2BapOBg%3D&st=2019-11-20T03%3A35%3A41Z&se=2019-12-21T03%3A40%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[2816076](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/2816076c25308a0f607f83c0a9fc1dd9c881ae9b)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[2816076](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/2816076c25308a0f607f83c0a9fc1dd9c881ae9b)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C20%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201911200341012569-2184%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=K9JabjM%2BHMlF4Pi3p%2BkZH%2F6Sd5hELY8%2FZMpI%2Fo4vdvo%3D&st=2019-11-20T03%3A36%3A38Z&se=2019-12-21T03%3A41%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
