### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[2d1f1bc](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/2d1f1bc574a881ad9ea473f91c66cc5f62bef2b9)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[2d1f1bc](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/2d1f1bc574a881ad9ea473f91c66cc5f62bef2b9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-6063) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C6%5C7%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202006071104598736-6063%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=35tkiEPvZQ6z3ZCYzDiLnzADlxSjTWVu2dPvIvKmWAc%3D&st=2020-06-07T11%3A00%3A31Z&se=2020-07-08T11%3A05%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://opportal-sandbox.azurewebsites.net/#/repos/8b165afe-a866-8c48-e5c3-ead94440f27e?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[7ecfd2e](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/7ecfd2e238b0771c555d55260063c4fd2f88380a)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[7ecfd2e](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/7ecfd2e238b0771c555d55260063c4fd2f88380a)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C6%5C7%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202006071106002150-6063%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2c%2Fbrg56b220IEbZwkR%2FntGgVlL0%2BkX4yJUflYiBBq8%3D&st=2020-06-07T11%3A01%3A30Z&se=2020-07-08T11%3A06%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://opportal-sandbox.azurewebsites.net/#/repos/8b165afe-a866-8c48-e5c3-ead94440f27e?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request closed without merging**
