### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[6e264ca](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/6e264ca3df1faa97c068798a2b76522ebdb2ef42)_: 

:clock10: **Pending**: waiting for processors ([15](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 15 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[6e264ca](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/6e264ca3df1faa97c068798a2b76522ebdb2ef42)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-5534) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C5%5C12%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202005121107114471-5534%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YBB1FKU0z7Nq3%2BuqnweD14aIJaZf6V5UMnxMkJr9CZw%3D&st=2020-05-12T11%3A03%3A07Z&se=2020-06-12T11%3A08%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[c2765c7](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/c2765c73ea76f2113833b68457b18cce5d00b0fa)_: 

:clock10: **Pending**: waiting for processors ([15](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 15 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[c2765c7](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/c2765c73ea76f2113833b68457b18cce5d00b0fa)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C5%5C12%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202005121108163059-5534%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hSKmHQqQVvrXkXmtxka7fADCCzX9WKZuieK%2BkiLIZwA%3D&st=2020-05-12T11%3A04%3A10Z&se=2020-06-12T11%3A09%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
