### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[5786214](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/5786214cf1be8db4323ff85e8996274cb49c01c7)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[5786214](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/5786214cf1be8db4323ff85e8996274cb49c01c7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-5628) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C5%5C17%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202005171105476939-5628%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6W8jx3ck9fArqOLE5%2BPAisfdEiviXNqgbeSNF8PBH1Y%3D&st=2020-05-17T11%3A01%3A37Z&se=2020-06-17T11%3A06%3A37Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[0b8ede9](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/0b8ede9283e026463e1a4940adc770cc240878b1)_: 

:clock10: **Pending**: waiting for processors ([8](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[0b8ede9](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/0b8ede9283e026463e1a4940adc770cc240878b1)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C5%5C17%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202005171106447451-5628%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3ptCx%2F%2BZr2zzCmGDG7tRqBzafQlPgB%2BonEtA0GRPP1Q%3D&st=2020-05-17T11%3A02%3A40Z&se=2020-06-17T11%3A07%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
