### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[a091a12](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/a091a1220e8ddf41098c4e01220f5f723c554e38)_: 

:clock10: **Pending**: waiting for processors ([18](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 18 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[a091a12](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/a091a1220e8ddf41098c4e01220f5f723c554e38)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-4493) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C19%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003191103018773-4493%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ifIIFhk7c0Tkib3bbLa4NjsJJI1qmAGTcUd4sabbiR4%3D&st=2020-03-19T10%3A58%3A59Z&se=2020-04-19T11%3A03%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[26b0640](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/26b0640d038da869fde5b31e0d7abd3cc80ee06d)_: 

:clock10: **Pending**: waiting for processors ([18](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 18 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[26b0640](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/26b0640d038da869fde5b31e0d7abd3cc80ee06d)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C19%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003191104093412-4493%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=90po4RxBbE3U0%2BS2wJ%2Bp%2FFYQWy1RL7vKIy1ClNfT%2FCk%3D&st=2020-03-19T10%3A59%3A54Z&se=2020-04-19T11%3A04%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
