### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[a6381eb](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/a6381ebd03e7d4ecdca0f88c865199e46d0fe3c4)_: 

:clock10: **Pending**: waiting for processors ([14](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 14 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[a6381eb](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/a6381ebd03e7d4ecdca0f88c865199e46d0fe3c4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-4668) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C30%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003301104355179-4668%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DqOuyZ4DF4n9ekSptXqqC800py53CXUtXEFz%2BizsBQc%3D&st=2020-03-30T11%3A00%3A36Z&se=2020-04-30T11%3A05%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[d9bf323](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/d9bf323d9dcfbc8ef5ee8c49018ff42ab5bd4138)_: 

:clock10: **Pending**: waiting for processors ([10](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[d9bf323](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/d9bf323d9dcfbc8ef5ee8c49018ff42ab5bd4138)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C30%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003301106408715-4668%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=E%2FsgeEdrzWHWXOiXccB2tZtlGrhNKkBJVFTdN5EzrQc%3D&st=2020-03-30T11%3A02%3A13Z&se=2020-04-30T11%3A07%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
