### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[6c4a328](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/6c4a3288eced4a2e29c883fbf131df11c8d3b9d3)_: 

:clock10: **Pending**: waiting for processors ([17](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 17 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[6c4a328](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/6c4a3288eced4a2e29c883fbf131df11c8d3b9d3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-4907) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C7%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004071104208443-4907%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FmSiRf5Fn58xi%2Fqrm0SXlVdm%2BaI4YMzL1qOGylUv6a8%3D&st=2020-04-07T10%3A59%3A55Z&se=2020-05-08T11%3A04%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[5e3f507](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/5e3f507d41b4629dfd55efbdaa669c301da06bce)_: 

:clock10: **Pending**: waiting for processors ([14](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 14 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[5e3f507](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/5e3f507d41b4629dfd55efbdaa669c301da06bce)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C7%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004071105222774-4907%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BMQfW7awak5lAq%2Fso0x8YPOEy0rcLfz4Lp5of5WLhpE%3D&st=2020-04-07T11%3A00%3A54Z&se=2020-05-08T11%3A05%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
