### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[d83477c](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/d83477cc8325d9ed8b4f64f765f720648174dfde)_: 

:clock10: **Pending**: waiting for processors ([13](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 13 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[d83477c](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/d83477cc8325d9ed8b4f64f765f720648174dfde)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-4718) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C1%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004011104124489-4718%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3A4tbmY9LNl%2B0ZVH%2BIACXKG5Q9tkvIzViguShFCc%2B1U%3D&st=2020-04-01T11%3A00%3A01Z&se=2020-05-02T11%3A05%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[cab4a57](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/cab4a570215edd2b04d2a4268aa5d66c04f6b5fb)_: 

:clock10: **Pending**: waiting for processors ([14](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 14 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[cab4a57](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/cab4a570215edd2b04d2a4268aa5d66c04f6b5fb)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C1%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004011105185817-4718%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=na4aeWBieOM3joPk9MaTZ8tOUHKCXU6a2b%2BsrWjdD3c%3D&st=2020-04-01T11%3A01%3A30Z&se=2020-05-02T11%3A06%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
