### PR TITLE
Incremental PR: add a resource and delete the added resource

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[f261cea](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/f261ceaf5af94f3212849d8ceca946094d3969b6)_: 

:clock10: **Pending**: waiting for processors ([17](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 17 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[f261cea](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/f261ceaf5af94f3212849d8ceca946094d3969b6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/incrementalPR-addresource.jpg](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addresource/E2E_DocsBranch_Dynamic/incrementalPR-addresource.jpg) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/incrementalpr-addresource.jpg?branch=pr-en-us-3782) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C2%5C13%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202002131127101876-3782%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6euTUOATMe2F7qgC6bs5wj7XGo%2BlHP6a%2BlnzPUnocVk%3D&st=2020-02-13T11%3A22%3A46Z&se=2020-03-15T11%3A27%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[e6e1d3e](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/e6e1d3e96392a74ff217abcf3d894d8aa353c90f)_: 

:clock10: **Pending**: waiting for processors ([17](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 17 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[e6e1d3e](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/e6e1d3e96392a74ff217abcf3d894d8aa353c90f)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C2%5C13%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202002131128134172-3782%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sxhrSImvbTDpeffLsIz3b8FNk7FwNZxNSme9%2Fcz6AKg%3D&st=2020-02-13T11%3A23%3A49Z&se=2020-03-15T11%3A28%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
