### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[dd04d00](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/dd04d00c763f08a0fa085a131fb884915fef5c26)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[dd04d00](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/dd04d00c763f08a0fa085a131fb884915fef5c26)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-3234) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C15%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001151104346898-3234%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=s2UUPe4H0zP2DrZdx%2BRjf8Xy1zqyshAuQPhnpNO9QQk%3D&st=2020-01-15T11%3A00%3A32Z&se=2020-02-15T11%3A05%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[be5a143](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/be5a143e97587bc29ab194537dae106d38957e72)_: 

:clock10: **Pending**: waiting for processors ([10](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[be5a143](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/be5a143e97587bc29ab194537dae106d38957e72)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C15%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001151106406454-3234%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2B8FZRsuMKiYUlv3%2Fgs4mRRMXPKRgx7tEyagb%2B001Uz0%3D&st=2020-01-15T11%3A02%3A19Z&se=2020-02-15T11%3A07%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
