### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[7965750](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/79657501bdfec63dd436772b923781a56eb29850)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[7965750](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/79657501bdfec63dd436772b923781a56eb29850)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-3741) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C2%5C12%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202002121103230426-3741%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=C9glnVAxyZShs6yCliwsvqLtr4usMOhF%2Fha9HP%2FMTGc%3D&st=2020-02-12T10%3A59%3A01Z&se=2020-03-14T11%3A04%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[dde9bb3](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/dde9bb3cc5c83e8a68f31a51c8a9d547450f8d38)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[dde9bb3](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/dde9bb3cc5c83e8a68f31a51c8a9d547450f8d38)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C2%5C12%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202002121104265793-3741%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ojImeIkM1P2T4LnEOjCehjzih4z0L53TAIVBsoTsij0%3D&st=2020-02-12T11%3A00%3A18Z&se=2020-03-14T11%3A05%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
