### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[7a73050](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/7a73050639b1976cf8c95c6222e5058a3cd0a86d)_: 

:clock10: **Pending**: waiting for processors ([5](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[7a73050](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/7a73050639b1976cf8c95c6222e5058a3cd0a86d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-4271) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C10%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003101119106643-4271%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eHYNnCR8tJjFSp6J9PusLStWPwfeQsphTFaD7qhsFMI%3D&st=2020-03-10T11%3A14%3A48Z&se=2020-04-10T11%3A19%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[299381b](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/299381bbd7337725d994e19b7210c690335ee275)_: 

:clock10: **Pending**: waiting for processors ([5](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[299381b](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/299381bbd7337725d994e19b7210c690335ee275)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C10%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003101120192292-4271%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=K7TqmPszy3cPyDMRRZRbqd6BVGzZjVTa7LENW%2BVIWa0%3D&st=2020-03-10T11%3A15%3A56Z&se=2020-04-10T11%3A20%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
