### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[df862b5](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/df862b573ec899c8940b7a3c53afe7ed8f93eb68)_: 

:clock10: **Pending**: waiting for processors ([16](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 16 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[df862b5](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/df862b573ec899c8940b7a3c53afe7ed8f93eb68)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-3624) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C2%5C6%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202002061105209636-3624%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cGPP0MUFFtad5XwdDOXJQQ226EqbURJ4VMZP80PTfbg%3D&st=2020-02-06T11%3A01%3A00Z&se=2020-03-08T11%3A06%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[73cc28f](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/73cc28f898dfd7e5857a1a85c413fe56dddc220f)_: 

:clock10: **Pending**: waiting for processors ([16](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 16 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[73cc28f](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/73cc28f898dfd7e5857a1a85c413fe56dddc220f)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C2%5C6%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202002061106264263-3624%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Nm%2Fz6pmq00Pu6kMBvbmN7zBCX%2FR2W3DiuvQsGXrUs1k%3D&st=2020-02-06T11%3A02%3A16Z&se=2020-03-08T11%3A07%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
