### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[72dd026](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/72dd0269f956b40a0651b3cfe6d298a4cfce8e1e)_: 

:clock10: **Pending**: waiting for processors ([20](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 20 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[72dd026](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/72dd0269f956b40a0651b3cfe6d298a4cfce8e1e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-3819) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C2%5C17%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202002171105221089-3819%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tjduuP1pkn2pWldybMi%2FfDMRwHcVlYzoaJUTu9gWeqw%3D&st=2020-02-17T11%3A00%3A59Z&se=2020-03-19T11%3A05%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[3225425](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/322542537d003da9f8955d7c71a2bdfa8a302fe8)_: 

:clock10: **Pending**: waiting for processors ([20](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 20 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[3225425](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/322542537d003da9f8955d7c71a2bdfa8a302fe8)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C2%5C17%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202002171106261164-3819%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hxHo1zs3nBz1Edvfrr4b%2BkzFV7aZmz1bRgCeYXa7jzE%3D&st=2020-02-17T11%3A02%3A04Z&se=2020-03-19T11%3A07%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
