### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[77a66b4](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/77a66b47e192a26f1c9eb384666613875461e26c)_: 

:clock10: **Pending**: waiting for processors ([18](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 18 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[77a66b4](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/77a66b47e192a26f1c9eb384666613875461e26c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-4568) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C24%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003241104119485-4568%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=E5vs%2Fb3eOeTeOCsnIEU4yc%2FOm7DS85DCIa7dBCu0Ctc%3D&st=2020-03-24T11%3A00%3A02Z&se=2020-04-24T11%3A05%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[49745cb](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/49745cbbb7b7aa7e0fef5bb89bdee5cced488da7)_: 

:clock10: **Pending**: waiting for processors ([10](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[49745cb](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/49745cbbb7b7aa7e0fef5bb89bdee5cced488da7)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C24%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003241105211450-4568%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UCF%2BsuOSszjiLFZmx3Eb1XPQCi%2Fgs%2FuEiAZ14EF3j2I%3D&st=2020-03-24T11%3A01%3A19Z&se=2020-04-24T11%3A06%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
