### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[6832da5](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/6832da58c7e001fe0c707b3e1004549fc1860399)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[6832da5](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/6832da58c7e001fe0c707b3e1004549fc1860399)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-5453) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C5%5C7%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202005071105299061-5453%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=niCby1TAar1U%2FRIikRg18daBYCDdFJ9YLpNFvMKFTQs%3D&st=2020-05-07T11%3A01%3A16Z&se=2020-06-07T11%3A06%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[dd73890](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/dd7389094578559949bca4faad62f2d68857b6c8)_: 

:clock10: **Pending**: waiting for processors ([7](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 7 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[dd73890](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/dd7389094578559949bca4faad62f2d68857b6c8)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C5%5C7%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202005071106310294-5453%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HyDbuJ2DdHmAffIyNe4VtG%2BX5OoVQZJ3BFfZG5JMfus%3D&st=2020-05-07T11%3A02%3A40Z&se=2020-06-07T11%3A07%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
