### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[11a86fd](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/11a86fd1fb540438cb375271ec7d45d70a7ad567)_: 

:clock10: **Pending**: waiting for processors ([16](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 16 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[11a86fd](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/11a86fd1fb540438cb375271ec7d45d70a7ad567)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-3449) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C28%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001281104372698-3449%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OWWM35dQdBVo4MQ0MmDsL88oFKaEAYXUT%2B2D45DZkRo%3D&st=2020-01-28T11%3A00%3A24Z&se=2020-02-28T11%3A05%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[51687c8](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/51687c85f5e676349e0b018134f5128ebdfa21f3)_: 

:clock10: **Pending**: waiting for processors ([16](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 16 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[51687c8](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/51687c85f5e676349e0b018134f5128ebdfa21f3)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C28%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001281105406041-3449%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BJzk%2BX5%2B9QdhPRSOuRMX5lyy2kFK22jXsXrXhKcReHU%3D&st=2020-01-28T11%3A01%3A36Z&se=2020-02-28T11%3A06%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
