### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[ed17651](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/ed1765179995bbabf2c1b0ed124ad31fcdd72ec1)_: 

:clock10: **Pending**: waiting for processors ([16](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 16 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[ed17651](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/ed1765179995bbabf2c1b0ed124ad31fcdd72ec1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-4694) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C31%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003311105375675-4694%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9azoLdJsWN5d5whQ515WnHpgiBV%2BhshEHnuBn77JmAU%3D&st=2020-03-31T11%3A01%3A16Z&se=2020-05-01T11%3A06%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[29de6eb](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/29de6eb2e06ce7915e13e906638efb719a0a1271)_: 

:clock10: **Pending**: waiting for processors ([9](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[29de6eb](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/29de6eb2e06ce7915e13e906638efb719a0a1271)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C31%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003311106400450-4694%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aa6Y%2FLAYAnQHA3dDJqJIZIemFIna6%2Fcj06gAtLN3L5s%3D&st=2020-03-31T11%3A02%3A18Z&se=2020-05-01T11%3A07%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
