### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[674645c](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/674645c9bd15e09bbd24c859879c452449bf2bda)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[674645c](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/674645c9bd15e09bbd24c859879c452449bf2bda)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-3475) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C29%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001291104202963-3475%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=75T7VHFaawilIfnPLUj4UGc0QkZq8jAYZQmZZDxBcXc%3D&st=2020-01-29T10%3A59%3A59Z&se=2020-02-29T11%3A04%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[9d6ec48](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9d6ec48ed9434cc5b6f26423cc8c8378b8416058)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[9d6ec48](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9d6ec48ed9434cc5b6f26423cc8c8378b8416058)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C29%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001291105251404-3475%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HKggSWTrt55SvQB334opjI%2Bqm9w098qbc7znkBv5J94%3D&st=2020-01-29T11%3A01%3A02Z&se=2020-02-29T11%3A06%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
