### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[e920df7](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/e920df7d369553c110e6204c8dcff8830f42238e)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[e920df7](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/e920df7d369553c110e6204c8dcff8830f42238e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-1392) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C2%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201910021103079436-1392%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5Hww9eq2NIljviQGs1QjXSMyGaZ4KkGAh013kuWke7k%3D&st=2019-10-02T10%3A58%3A56Z&se=2019-11-02T11%3A03%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[43c11ae](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/43c11aec106b1d27f57367a727c652f1cf4a353a)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[43c11ae](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/43c11aec106b1d27f57367a727c652f1cf4a353a)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C2%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201910021104075084-1392%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hC5fy07gRlFgrLHL1Xb17AnhhJoqa47o1KxHkS60rak%3D&st=2019-10-02T10%3A59%3A40Z&se=2019-11-02T11%3A04%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
