### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[8a4a556](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/8a4a55640d716ae11e42e942d0264a983be15197)_: 

:clock10: **Pending**: waiting for processors ([10](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[8a4a556](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/8a4a55640d716ae11e42e942d0264a983be15197)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-922) | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C8%5C19%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201908191806359449-922%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bYSlSk2aSKwHISg8Zuitx6OMRThLUAfDmUIQwtiv0C0%3D&st=2019-08-19T18%3A02%3A10Z&se=2019-09-19T18%3A07%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[3834823](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/383482360d6fac927ef756ba6b58d2dd29f345b5)_: 

:clock10: **Pending**: waiting for processors ([10](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by v-minnli** [comment]
Docs Build status updates of commit _[3834823](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/383482360d6fac927ef756ba6b58d2dd29f345b5)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C8%5C19%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201908191807309721-922%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YjKvOJZqZEvSSbghStaKfOaNeW5kO2jmWjpf%2ByTqUSg%3D&st=2019-08-19T18%3A03%3A03Z&se=2019-09-19T18%3A08%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
