### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[1eeacb2](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/1eeacb2f770f97ef1eb4583c92f2247306413d2c)_: 

:clock10: **Pending**: waiting for processors ([13](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 13 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[1eeacb2](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/1eeacb2f770f97ef1eb4583c92f2247306413d2c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2767) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C23%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912231103127141-2767%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6z04SBVe714FkklAKh%2BJEDNJlYO3WrXPHrDJ2lzz0dU%3D&st=2019-12-23T10%3A58%3A51Z&se=2020-01-23T11%3A03%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[69d7438](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/69d7438006cbd2aba9fbc65ad4b03d183ff3bfc7)_: 

:clock10: **Pending**: waiting for processors ([13](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 13 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[69d7438](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/69d7438006cbd2aba9fbc65ad4b03d183ff3bfc7)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C23%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912231104209065-2767%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DS3HjiKdL1k2J6vOWX8UjHaz50cY8a6O4%2BmBx0INBHY%3D&st=2019-12-23T11%3A00%3A09Z&se=2020-01-23T11%3A05%3A09Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
