### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[15314ca](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/15314cac4fea956332634c99da0cd5f8fcfac2ca)_: 

:clock10: **Pending**: waiting for processors ([9](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[15314ca](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/15314cac4fea956332634c99da0cd5f8fcfac2ca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2011) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C8%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201911080645425583-2011%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wthX%2F%2BwvoLW1VSYXjj09OCoZkG8O0XL55pqLV7sd5rg%3D&st=2019-11-08T06%3A41%3A31Z&se=2019-12-09T06%3A46%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[31e8369](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/31e836958afdacbb80a9937ff3b4e5b302afd95c)_: 

:clock10: **Pending**: waiting for processors ([10](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[31e8369](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/31e836958afdacbb80a9937ff3b4e5b302afd95c)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C8%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201911080646507423-2011%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xWqCK3Hu93AL85J%2B00sKrnQDjFveSjCfO%2BAvZBXz%2F50%3D&st=2019-11-08T06%3A42%3A38Z&se=2019-12-09T06%3A47%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
