### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[9ad805e](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9ad805e79884bc296c2ee4d1cc9558d69c6a453e)_: 

:clock10: **Pending**: waiting for processors ([8](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[9ad805e](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9ad805e79884bc296c2ee4d1cc9558d69c6a453e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2914) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C31%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912311104207338-2914%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=z%2ByiuzyE%2BB8DkYIWY%2FY3WWmbiy1Z013EcAOlR3FIqz8%3D&st=2019-12-31T10%3A59%3A59Z&se=2020-01-31T11%3A04%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[19a8f1f](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/19a8f1f773322dcebaf58dde0dbc6930b7d5623b)_: 

:clock10: **Pending**: waiting for processors ([8](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[19a8f1f](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/19a8f1f773322dcebaf58dde0dbc6930b7d5623b)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C31%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912311105260899-2914%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jmKZCNUlACV1tLmr9Lo6E5sFXm3ejJmoJaIpGLtCZek%3D&st=2019-12-31T11%3A01%3A16Z&se=2020-01-31T11%3A06%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
