### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[b2f004b](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/b2f004b8c23a54e679598f32627d4f57f30df9b3)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[b2f004b](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/b2f004b8c23a54e679598f32627d4f57f30df9b3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-3138) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C9%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001091104294793-3138%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uVg277MvSmzGq23J8uqlZQ57BrPSD2ZAV%2FyuMWq6dJM%3D&st=2020-01-09T11%3A00%3A13Z&se=2020-02-09T11%3A05%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[8e2489e](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/8e2489e2dd391407d0c12c8b3454d96b6bf91ff6)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[8e2489e](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/8e2489e2dd391407d0c12c8b3454d96b6bf91ff6)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C9%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001091105362359-3138%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UixfSnvnumFAcWtLml1R37cQiiTeb8uEZyR4AchYu0E%3D&st=2020-01-09T11%3A01%3A21Z&se=2020-02-09T11%3A06%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
