### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[e11f781](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/e11f7816bfb67834a405252fccd4853a991eaeee)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[e11f781](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/e11f7816bfb67834a405252fccd4853a991eaeee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-1983) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C8%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201911080529116450-1983%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vsJktaYZo4OauSHDnNZ3KqQGpEUxPOHB%2Bq2JQAW3jOg%3D&st=2019-11-08T05%3A25%3A11Z&se=2019-12-09T05%3A30%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[7df87b0](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/7df87b05b83b38cbdf158224c6325f74b7b51915)_: 

:clock10: **Pending**: waiting for processors ([6](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[7df87b0](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/7df87b05b83b38cbdf158224c6325f74b7b51915)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C8%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201911080531208153-1983%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Dzo9h6qVODoWQbeEjtg6eTql%2FuLg18xGOLtmIUDwCow%3D&st=2019-11-08T05%3A27%3A00Z&se=2019-12-09T05%3A32%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
