### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[0f7ffe3](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/0f7ffe32cee0caf4253be8c0d41538d4cf5d7e5f)_: 

:clock10: **Pending**: waiting for processors ([17](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 17 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[0f7ffe3](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/0f7ffe32cee0caf4253be8c0d41538d4cf5d7e5f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-5423) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C5%5C6%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202005061105126524-5423%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Uh5cnkfSdDdg2JEXCls2kBUKdd7z5%2FDPcUYX8OlUxSk%3D&st=2020-05-06T11%3A01%3A07Z&se=2020-06-06T11%3A06%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[b5c5d32](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/b5c5d328292039d73bcd98293da7a12eeb4da9f8)_: 

:clock10: **Pending**: waiting for processors ([17](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 17 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[b5c5d32](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/b5c5d328292039d73bcd98293da7a12eeb4da9f8)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C5%5C6%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202005061106163521-5423%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lYe89qW4OpuglLNULNWKELolZX2w%2B2P7g5vv%2B44chpg%3D&st=2020-05-06T11%3A02%3A00Z&se=2020-06-06T11%3A07%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
