### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[5bd27fe](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/5bd27fee36b8b27bd557b90346dc08cb518cef96)_: 

:clock10: **Pending**: waiting for processors ([15](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 15 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[5bd27fe](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/5bd27fee36b8b27bd557b90346dc08cb518cef96)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-4837) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C6%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004061104199612-4837%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BvpujV8Vy%2Fx%2BTzVPqML3p26Kq%2FBBSE6%2FCkF%2Bk0neJb4%3D&st=2020-04-06T10%3A59%3A54Z&se=2020-05-07T11%3A04%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[9f09172](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9f0917224d21a93bfb4f07f2cdd993f36463d702)_: 

:clock10: **Pending**: waiting for processors ([7](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 7 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[9f09172](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9f0917224d21a93bfb4f07f2cdd993f36463d702)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C6%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004061105195580-4837%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7bn5d0QRJtczQUJed2NoT%2FZ%2BaIFXBJSgc7Vn63vsB3Q%3D&st=2020-04-06T11%3A00%3A55Z&se=2020-05-07T11%3A05%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
