### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[da1a332](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/da1a332cd1d8d2518723489f1298af927ef4baa6)_: 

:clock10: **Pending**: waiting for processors ([17](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 17 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[da1a332](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/da1a332cd1d8d2518723489f1298af927ef4baa6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2518) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C9%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912091238354450-2518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ElKI4ePrjkjE%2F0n8BLFy8lXgLvsGh%2BTRsRpzkC0azyI%3D&st=2019-12-09T12%3A35%3A03Z&se=2020-01-09T12%3A40%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[cd04b72](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/cd04b728d115bfdb751edab86d77507500345f82)_: 

:clock10: **Pending**: waiting for processors ([14](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 14 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[cd04b72](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/cd04b728d115bfdb751edab86d77507500345f82)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C9%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912091240332039-2518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MD7rW4xtgFXcmKweJL7n%2B6oc4jKBPTjd9pybki5O%2Fac%3D&st=2019-12-09T12%3A36%3A45Z&se=2020-01-09T12%3A41%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
