### PR TITLE
v3 pull request edit button

### PR DESCRIPTION
**Pull request by luyajun0205**

### CODE REVIEW

**Comment by staceyhong** [comment]
OPS Build status updates of commit _[fcfee71](https://github.com/RepoTransferOrg/E2E_DocFxV3/pull/91/commits/fcfee71b985d5c4f08b1fae6b24878b1a9a9c6b4)_: 

:clock10: **Preparing**: average preparing time is not available, there is no data for this repository.

**Comment by luyajun0205** [comment]
OPS Build status updates of commit _[fcfee71](https://github.com/RepoTransferOrg/E2E_DocFxV3/pull/91/commits/fcfee71b985d5c4f08b1fae6b24878b1a9a9c6b4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[E2E_DocsBranch_Dynamic/a.md](https://github.com/RepoTransferOrg/E2E_DocFxV3/blob/prEditButton-v3/E2E_DocsBranch_Dynamic/a.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/a?branch=pr-en-us-91) | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C2%5C3%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201902030236400829-91%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=IAzCtKJbRhnnVXdkE%2BKuWJNe3icuecJkP7m9DrnMKds%3D&st=2019-02-03T02%3A33%3A32Z&se=2019-03-06T02%3A38%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
OPS Build status updates of commit _[7a8a136](https://github.com/RepoTransferOrg/E2E_DocFxV3/pull/91/commits/7a8a1369a500cc27ea43a587706f2db35c5d4ad9)_: 

:clock10: **Preparing**: average preparing time is not available, there is no data for this repository.

**Comment by luyajun0205** [comment]
OPS Build status updates of commit _[7a8a136](https://github.com/RepoTransferOrg/E2E_DocFxV3/pull/91/commits/7a8a1369a500cc27ea43a587706f2db35c5d4ad9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[E2E_DocsBranch_Dynamic/a.md](https://github.com/RepoTransferOrg/E2E_DocFxV3/blob/prEditButton-v3/E2E_DocsBranch_Dynamic/a.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/a?branch=pr-en-us-91) | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C2%5C11%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201902110738221516-91%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=kbNWWRUnf53iJE0md1B9J%2Fw1UUoVGamsCCskzaMiclY%3D&st=2019-02-11T07%3A35%3A46Z&se=2019-03-14T07%3A40%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
