### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[d09a3ef](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/d09a3ef2606cf3608ef6734661acd17be5e12a75)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[d09a3ef](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/d09a3ef2606cf3608ef6734661acd17be5e12a75)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-1297) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C25%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201909251104459535-1297%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=curggWrXyrxfc3bm1U69EjuSDw9zSNDDZgbej%2F6AWKc%3D&st=2019-09-25T11%3A00%3A25Z&se=2019-10-26T11%3A05%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[8a569b8](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/8a569b83a84980ae923ea3cda27880baacaaef9b)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[8a569b8](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/8a569b83a84980ae923ea3cda27880baacaaef9b)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C25%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201909251105472687-1297%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XATtVRW3O7EhFaqxCOBq4YSbzYTjVzSmtt229ih71Sg%3D&st=2019-09-25T11%3A01%3A23Z&se=2019-10-26T11%3A06%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
