### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[597c7cf](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/597c7cfaaee749b8a3e5494bd051800704eeee3c)_: 

:clock10: **Pending**: waiting for processors ([15](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 15 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[597c7cf](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/597c7cfaaee749b8a3e5494bd051800704eeee3c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-4822) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C6%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004060949441745-4822%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ad7XmPITnIoKCR4Z0e3iPkpn7bUIiGG64oJ7YhWHYzI%3D&st=2020-04-06T09%3A45%3A13Z&se=2020-05-07T09%3A50%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[e705852](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/e7058520b17f195ac949b6aed08b8e069059f959)_: 

:clock10: **Pending**: waiting for processors ([8](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[e705852](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/e7058520b17f195ac949b6aed08b8e069059f959)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C6%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004060950484752-4822%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=m5dD0JKC2oagj6vgMSszW0dilMiRdcUXms7Y0t4HgfY%3D&st=2020-04-06T09%3A46%3A31Z&se=2020-05-07T09%3A51%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
