### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[eacd5df](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/eacd5dfa80b34543f0abf5792e30ae3331050187)_: 

:clock10: **Pending**: waiting for processors ([15](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 15 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[eacd5df](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/eacd5dfa80b34543f0abf5792e30ae3331050187)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-4618) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C26%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003261103005765-4618%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gBRuVlrPoGZx6dGTM%2B1G4Mruhja4BVd5iY3u%2BDWVuXo%3D&st=2020-03-26T10%3A58%3A33Z&se=2020-04-26T11%3A03%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[f30eeee](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/f30eeee223b1665b022054709206c3db0129fb5a)_: 

:clock10: **Pending**: waiting for processors ([15](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 15 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[f30eeee](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/f30eeee223b1665b022054709206c3db0129fb5a)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C26%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003261104070496-4618%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ptwmN%2FR6DVW%2Bo6LJ1fcTbZ5beopqeOB2RiJh6V1NM%2FI%3D&st=2020-03-26T10%3A59%3A53Z&se=2020-04-26T11%3A04%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
