### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[366e241](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/366e241139a00affab1848d0cce700ad34622ff5)_: 

:clock10: **Pending**: waiting for processors ([9](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[366e241](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/366e241139a00affab1848d0cce700ad34622ff5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2139) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C18%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201911180228491692-2139%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4PvkOTdA%2B9hkXP%2B%2FpXp7oJa6IGVK6z2pn1RP0vfvHP8%3D&st=2019-11-18T02%3A24%3A44Z&se=2019-12-19T02%3A29%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[58d7fdb](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/58d7fdb0fa595eb705e7f4ad6030ec399994f3f8)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[58d7fdb](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/58d7fdb0fa595eb705e7f4ad6030ec399994f3f8)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C18%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201911180230449627-2139%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1l8yt820i%2B2hXHWdlTny87XHfBll0Io2uQUFn2I%2FfBo%3D&st=2019-11-18T02%3A26%3A27Z&se=2019-12-19T02%3A31%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
