### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[ae937c6](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/ae937c6ea2ce09d2089204c0b5e9a3d1a9427a2d)_: 

:clock10: **Pending**: waiting for processors ([15](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 15 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[ae937c6](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/ae937c6ea2ce09d2089204c0b5e9a3d1a9427a2d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-5506) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C5%5C11%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202005111103085110-5506%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=O9B2MeJ2ZHn8XSKrIfErTXYSXy5enFxtJYho5H6tVfU%3D&st=2020-05-11T10%3A58%3A36Z&se=2020-06-11T11%3A03%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[edce87c](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/edce87c0709c0ad8967d48d40140a1d497d49bf1)_: 

:clock10: **Pending**: waiting for processors ([15](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 15 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[edce87c](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/edce87c0709c0ad8967d48d40140a1d497d49bf1)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C5%5C11%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202005111104138929-5506%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ov8YYZsIcl1Wju7ChkWvNBm2U3ExWtpJ70H06bjLJjA%3D&st=2020-05-11T10%3A59%3A57Z&se=2020-06-11T11%3A04%3A57Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
