### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[55af9a1](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/55af9a13b331526af1b5e6f60044c1a1b237359d)_: 

:clock10: **Pending**: waiting for processors ([7](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 7 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[55af9a1](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/55af9a13b331526af1b5e6f60044c1a1b237359d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-3091) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C8%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001081103205232-3091%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wlGf0tLOtE5kzxyGI8bU2RCn0iZdNljrWjzoq2Yrm%2Bc%3D&st=2020-01-08T10%3A58%3A59Z&se=2020-02-08T11%3A03%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[7d30f96](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/7d30f962a46b21aa2aabda82fd0721df09190c57)_: 

:clock10: **Pending**: waiting for processors ([7](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 7 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[7d30f96](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/7d30f962a46b21aa2aabda82fd0721df09190c57)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C8%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001081104276152-3091%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=szqbHWI3gr50pGDa66tMfka1gFhOnEkF4IOYcZhRM2I%3D&st=2020-01-08T11%3A00%3A11Z&se=2020-02-08T11%3A05%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
