### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[3ef1157](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/3ef1157c9edd93b081e057cb57e6f9b218349208)_: 

:clock10: **Pending**: waiting for processors ([9](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[3ef1157](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/3ef1157c9edd93b081e057cb57e6f9b218349208)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-5004) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C12%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004121103357040-5004%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QddZyH4lexkTQDqt3oQhP1YHzvrdeYr7VG7xP9DgIlw%3D&st=2020-04-12T10%3A59%3A11Z&se=2020-05-13T11%3A04%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[82ad613](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/82ad6134094671f23624b6786156ae0575672a29)_: 

:clock10: **Pending**: waiting for processors ([13](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 13 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[82ad613](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/82ad6134094671f23624b6786156ae0575672a29)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C12%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004121104320361-5004%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6y6f5W1a2tcKdtecDSEThcZ0voDPgEW7g7b3hNEa94w%3D&st=2020-04-12T11%3A00%3A03Z&se=2020-05-13T11%3A05%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
