### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[8b96bab](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/8b96babeb46004dec60bdf5a4eae1965c46e0151)_: 

:clock10: **Pending**: waiting for processors ([8](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[8b96bab](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/8b96babeb46004dec60bdf5a4eae1965c46e0151)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-5194) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C21%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004211103221419-5194%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TEBUmfXc9Ne51wa0HcLDx35O5z2GoKcwavWCw2r9woQ%3D&st=2020-04-21T10%3A59%3A06Z&se=2020-05-22T11%3A04%3A06Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[dcb1e14](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/dcb1e14a93c77d3cccca1e33eb72c54758e8bbee)_: 

:clock10: **Pending**: waiting for processors ([8](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[dcb1e14](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/dcb1e14a93c77d3cccca1e33eb72c54758e8bbee)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C21%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004211104247095-5194%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=e2VJdMkIO2Sr5MMJ3VcUSGiQb8CagHQjgMKsFlAoEd0%3D&st=2020-04-21T11%3A00%3A13Z&se=2020-05-22T11%3A05%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
