### PR TITLE
Pull request error status testing

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by v-peliao** [comment]
Docs Build status updates of commit _[d3cc21d](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/pull/439/commits/d3cc21d63d48758d457a9ecee3c6832d1dd4f7bc)_: 

:clock10: **Pending**: waiting for processors ([10](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[d3cc21d](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/pull/439/commits/d3cc21d63d48758d457a9ecee3c6832d1dd4f7bc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[E2E_DocsBranch_Dynamic/index.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/prError-e2e/E2E_DocsBranch_Dynamic/index.md) | :white_check_mark:Succeeded | | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C5%5C29%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201905290146495915-439%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=q%2FA1cZUBngHPZX%2BqW5hgyrOzw5iLm0ghaYNVxLWLLH8%3D&st=2019-05-29T01%3A42%3A21Z&se=2019-06-29T01%3A47%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[d3cc21d](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/pull/439/commits/d3cc21d63d48758d457a9ecee3c6832d1dd4f7bc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[E2E_DocsBranch_Dynamic/index.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/prError-e2e/E2E_DocsBranch_Dynamic/index.md) | :white_check_mark:Succeeded | | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C5%5C29%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201905290216559286-439%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yHqu3JFsuIB5xYHKMEXJS3epdGLSLiholbPafE96rQE%3D&st=2019-05-29T02%3A24%3A56Z&se=2019-06-29T02%3A29%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[d3cc21d](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/pull/439/commits/d3cc21d63d48758d457a9ecee3c6832d1dd4f7bc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[E2E_DocsBranch_Dynamic/index.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/prError-e2e/E2E_DocsBranch_Dynamic/index.md) | :white_check_mark:Succeeded | | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C5%5C29%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201905291117594515-439%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fX4ZDMwXrK0gZIDuqxoLUmLEVyngzdxEXE6EiXd3dvY%3D&st=2019-05-29T11%3A13%3A43Z&se=2019-06-29T11%3A18%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[d3cc21d](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/pull/439/commits/d3cc21d63d48758d457a9ecee3c6832d1dd4f7bc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[E2E_DocsBranch_Dynamic/index.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/prError-e2e/E2E_DocsBranch_Dynamic/index.md) | :white_check_mark:Succeeded | | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C5%5C29%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201905291119195073-439%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ov0iR9kcdPbAQ0uJ7W%2FIQrikxauw5SCzAfoE4dXMf1k%3D&st=2019-05-29T11%3A14%3A50Z&se=2019-06-29T11%3A19%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
