### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[5bddd41](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/5bddd41788147dddc4aaf3321e68728750aa0178)_: 

:clock10: **Pending**: waiting for processors ([9](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[5bddd41](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/5bddd41788147dddc4aaf3321e68728750aa0178)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-1458) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C8%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201910081104197825-1458%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NiDkc18CGqJ8bglZoBEqM4koTyKYzOw3kSntWhby8UU%3D&st=2019-10-08T10%3A59%3A59Z&se=2019-11-08T11%3A04%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[55c6137](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/55c61372db2e322e46830db029c0726f2d6dad81)_: 

:clock10: **Pending**: waiting for processors ([8](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[55c6137](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/55c61372db2e322e46830db029c0726f2d6dad81)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C8%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201910081105302181-1458%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=17d21sVrmLFghvAISCyw5nPqu3Vcdjfj4hjx%2BsTDH18%3D&st=2019-10-08T11%3A01%3A01Z&se=2019-11-08T11%3A06%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
