### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[9ae6bac](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9ae6bace4da3fc9071443e9c4bce949137f429df)_: 

:clock10: **Pending**: waiting for processors ([34](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 34 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[9ae6bac](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9ae6bace4da3fc9071443e9c4bce949137f429df)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-4844) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C6%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004061109184553-4844%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2A0DBtg62XvhFEyrlo6wY7ZWWJFHoIFeim%2Bs8AT0bjA%3D&st=2020-04-06T11%3A04%3A59Z&se=2020-05-07T11%3A09%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[ce63cb0](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/ce63cb0b8c42c49e51b8da39021c4007204e6015)_: 

:clock10: **Pending**: waiting for processors ([34](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 34 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[ce63cb0](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/ce63cb0b8c42c49e51b8da39021c4007204e6015)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C6%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004061110189034-4844%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MepVWBjEm5Z3deNDIYzPzoeNE2zLva%2FMcy6kdGfJ1M4%3D&st=2020-04-06T11%3A06%3A16Z&se=2020-05-07T11%3A11%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
