### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[df07790](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/df077909a58d5ceefa056333d1db7e6e40fdeb34)_: 

:clock10: **Pending**: waiting for processors ([17](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 17 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[df07790](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/df077909a58d5ceefa056333d1db7e6e40fdeb34)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-3210) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C14%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001141105272496-3210%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kM1Vfi9YqnWKvER9A8iZ8cJxIz3xFtDWHbI4Y1ZJjhw%3D&st=2020-01-14T11%3A01%3A10Z&se=2020-02-14T11%3A06%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[19c0d72](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/19c0d726b22305e7ab0afc3b2eca218347a8814a)_: 

:clock10: **Pending**: waiting for processors ([9](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[19c0d72](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/19c0d726b22305e7ab0afc3b2eca218347a8814a)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C14%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001141106325483-3210%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3jKn%2BbP6EROA8i33rutSIUGfTr0K3csRqk24adsGFCs%3D&st=2020-01-14T11%3A02%3A24Z&se=2020-02-14T11%3A07%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
