### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[df6f338](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/df6f338139d87c57198fa8a5152bd6f79db3b897)_: 

:clock10: **Pending**: waiting for processors ([13](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 13 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[df6f338](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/df6f338139d87c57198fa8a5152bd6f79db3b897)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2400) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C2%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912021104037702-2400%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=e9D%2FkTfm3H7DTtRMYXL0z7oRhSEBtmCfOuAOLlstV3o%3D&st=2019-12-02T10%3A59%3A48Z&se=2020-01-02T11%3A04%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[e59e026](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/e59e026f250c9788877e3568d3e7751066f75c7b)_: 

:clock10: **Pending**: waiting for processors ([7](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 7 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[e59e026](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/e59e026f250c9788877e3568d3e7751066f75c7b)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C2%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912021105117001-2400%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jal82N%2BTITgwu11pbYYKM1qxr1uxIrDQiPIm1p%2FJZ8g%3D&st=2019-12-02T11%3A00%3A56Z&se=2020-01-02T11%3A05%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
