### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[9c38516](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9c38516620fb1e8fa2806bb353449989cc74e2ff)_: 

:clock10: **Pending**: waiting for processors ([17](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 17 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[9c38516](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9c38516620fb1e8fa2806bb353449989cc74e2ff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-3574) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C2%5C4%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202002041105266182-3574%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FgQdBJ0uiY25rtYOR60EAHmT4DPz6CG0Ahl8BglYNMY%3D&st=2020-02-04T11%3A01%3A18Z&se=2020-03-06T11%3A06%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[18ab344](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/18ab34497197bab32d54d2cabca53534b547799a)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[18ab344](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/18ab34497197bab32d54d2cabca53534b547799a)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C2%5C4%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202002041106305701-3574%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=z3kUGyd%2BfKyl2seJEk52MjMCG3JvvW8idS%2F7lgTs1TY%3D&st=2020-02-04T11%3A02%3A15Z&se=2020-03-06T11%3A07%3A15Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
