### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[158cc36](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/158cc360d553320d4441b8fb9268b81119d1c88a)_: 

:clock10: **Pending**: waiting for processors ([5](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[158cc36](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/158cc360d553320d4441b8fb9268b81119d1c88a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :bulb:Suggestion | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-1087) | [Details](#user-content-b441094d-e6c442e0)

<a id="b441094d-e6c442e0"></a>
### [E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md)
 - **Line 0**: **[Suggestion]** `````Missing required attribute: 'author'. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````
 - **Line 0**: **[Suggestion]** `````Missing required attribute: 'title'. Add a title string to show in search engine results. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C4%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201909041802400748-1087%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Gu1Z%2FVd%2F0fsT3K%2BWhSa8rt%2FQ5cLexmcmj3rfSh7Zwh4%3D&st=2019-09-04T17%3A58%3A18Z&se=2019-10-05T18%3A03%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[45ca12e](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/45ca12e903c5ffcdf698dec30fba0480ea5c15f4)_: 

:clock10: **Pending**: waiting for processors ([5](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[45ca12e](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/45ca12e903c5ffcdf698dec30fba0480ea5c15f4)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C4%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201909041803404837-1087%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NL4zSBlYMG8gj18Sx9FcG7RHbHdC8q3lD3DTSPiwNHo%3D&st=2019-09-04T17%3A59%3A11Z&se=2019-10-05T18%3A04%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
