### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[68dd992](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/68dd9925ff9963727821d87a881ca8ba5dea164f)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[68dd992](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/68dd9925ff9963727821d87a881ca8ba5dea164f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :bulb:Suggestion | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-1061) | [Details](#user-content-b441094d-71cd1f09)

<a id="b441094d-71cd1f09"></a>
### [E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md)
 - **Line 0**: **[Suggestion]** `````Missing required attribute: 'author'. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````
 - **Line 0**: **[Suggestion]** `````Missing required attribute: 'title'. Add a title string to show in search engine results. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C2%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201909021803014830-1061%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2B5Mi3ck8PCXhFqoZZ%2BxTM8OavBkuGzPusX0galUlZPs%3D&st=2019-09-02T17%3A58%3A39Z&se=2019-10-03T18%3A03%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[05e4109](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/05e4109f4444876ddafba7824af8e501c9f9bd41)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[05e4109](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/05e4109f4444876ddafba7824af8e501c9f9bd41)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C2%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201909021803588026-1061%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DuAXaZTQfYfJt7LTJ8WOkAKnhkOaRozSDMJqY0sx9S4%3D&st=2019-09-02T17%3A59%3A38Z&se=2019-10-03T18%3A04%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
