### PR TITLE
Incremental PR: add a resource and delete the added resource

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[b7ff1c3](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/b7ff1c3cd1040fad5969f161434043bb5f08428b)_: 

:clock10: **Pending**: waiting for processors ([6](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[b7ff1c3](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/b7ff1c3cd1040fad5969f161434043bb5f08428b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/incrementalPR-addresource.jpg](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addresource/E2E_DocsBranch_Dynamic/incrementalPR-addresource.jpg) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/incrementalpr-addresource.jpg?branch=pr-en-us-5671) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C5%5C18%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202005181152548651-5671%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NMYISzwf%2BZ8p4i%2B5x%2BmVap6uK7aaWpgaagsDSdqNCwk%3D&st=2020-05-18T11%3A48%3A39Z&se=2020-06-18T11%3A53%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[f3a3b51](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/f3a3b51c9be7bb0767f52cb89465c39919fb68b5)_: 

:clock10: **Pending**: waiting for processors ([6](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[f3a3b51](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/f3a3b51c9be7bb0767f52cb89465c39919fb68b5)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C5%5C18%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202005181154017258-5671%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iBKIgTtJrrEiDFBCGofUW%2BuyYu1Q7OwKqrd6UX9bQts%3D&st=2020-05-18T11%3A49%3A52Z&se=2020-06-18T11%3A54%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[f3a3b51](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/f3a3b51c9be7bb0767f52cb89465c39919fb68b5)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C5%5C18%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202005181154017258-5671%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DiXMnKOYGLDUMeIJeuR2IIQAMz7Oy2oV5wVzHlGy%2BXE%3D&st=2020-05-18T11%3A53%3A28Z&se=2020-06-18T11%3A58%3A28Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
