### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[29411f7](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/29411f784bc5c16e226c9bc1b519174aeb49fdc7)_: 

:clock10: **Pending**: waiting for processors ([17](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 17 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[29411f7](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/29411f784bc5c16e226c9bc1b519174aeb49fdc7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-4595) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C25%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003251106393987-4595%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zWEbb05ImzLpimDExDr2nHmk02bkYsz%2BWcMaeftXzGE%3D&st=2020-03-25T11%3A02%3A32Z&se=2020-04-25T11%3A07%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[79be2b3](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/79be2b34e767f10cd8cb637d09b8f8b51167338f)_: 

:clock10: **Pending**: waiting for processors ([17](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 17 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[79be2b3](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/79be2b34e767f10cd8cb637d09b8f8b51167338f)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C25%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003251107387758-4595%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jmko2kvZnEOuR8mYWU%2FCBHJADButTtGzEYKOBf3ASw4%3D&st=2020-03-25T11%3A03%3A37Z&se=2020-04-25T11%3A08%3A37Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
