### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[1acafe9](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/1acafe9a909404a6f3bd849fd23b504ec617858e)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[1acafe9](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/1acafe9a909404a6f3bd849fd23b504ec617858e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :bulb:Suggestion | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-1126) | [Details](#user-content-b441094d-1c791406)

<a id="b441094d-1c791406"></a>
### [E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md)
 - **Line 0**: **[Suggestion]** `````Missing required attribute: 'author'. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````
 - **Line 0**: **[Suggestion]** `````Missing required attribute: 'title'. Add a title string to show in search engine results. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C9%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201909091803195672-1126%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Nm%2FaDYMpzbrBowreeglimujHHskILae4rE1u8HH7Ypc%3D&st=2019-09-09T17%3A58%3A58Z&se=2019-10-10T18%3A03%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[5c467bd](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/5c467bd43d63f8dbc994b1a6586bb2a46cb0d2f7)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[5c467bd](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/5c467bd43d63f8dbc994b1a6586bb2a46cb0d2f7)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C9%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201909091804175803-1126%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qgL0%2FmuxXzDgUrbTacF7zkaR0d7UKF%2FZk37LetQlkKg%3D&st=2019-09-09T18%3A00%3A07Z&se=2019-10-10T18%3A05%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
