### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[6b65604](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/6b65604b8ebafb758cea6783f13355d87d54ac91)_: 

:clock10: **Pending**: waiting for processors ([16](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 16 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[6b65604](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/6b65604b8ebafb758cea6783f13355d87d54ac91)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-3187) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C13%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001131105320248-3187%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GEM78gVFrqMXm56wwL8VAv3q8p0dl2CzNv0%2BX65%2FWa4%3D&st=2020-01-13T11%3A01%3A13Z&se=2020-02-13T11%3A06%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[e25e7c5](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/e25e7c5b5b8e03ac08eac6df1c92339c9edf5792)_: 

:clock10: **Pending**: waiting for processors ([7](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 7 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[e25e7c5](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/e25e7c5b5b8e03ac08eac6df1c92339c9edf5792)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C13%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001131106353961-3187%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=88h0AH6A3XmIKzC0T3ERUErOQ5vzXPNS356duIvmQFQ%3D&st=2020-01-13T11%3A02%3A13Z&se=2020-02-13T11%3A07%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
