### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[6733044](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/67330445b472900475807dde3a12c495dc772911)_: 

:clock10: **Pending**: waiting for processors ([21](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 21 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[6733044](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/67330445b472900475807dde3a12c495dc772911)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-3067) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C7%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001071107221387-3067%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2cDZC0z2WeERnfXmC5HaLS6PZz9PuBVUp1IxnM3GAKk%3D&st=2020-01-07T11%3A03%3A10Z&se=2020-02-07T11%3A08%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[5ec4036](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/5ec4036549f0a52ae5c9c8cc3a6559553136cd75)_: 

:clock10: **Pending**: waiting for processors ([21](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 21 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[5ec4036](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/5ec4036549f0a52ae5c9c8cc3a6559553136cd75)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C7%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001071108257863-3067%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=O2f%2BIpRbNEZ6uDnVVbOo93wBc25MxK1a8%2BpbgwbPkYk%3D&st=2020-01-07T11%3A04%3A09Z&se=2020-02-07T11%3A09%3A09Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
