### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[d9c071f](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/d9c071fa36db2f3fd1c33693451879a64834378b)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[d9c071f](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/d9c071fa36db2f3fd1c33693451879a64834378b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-5389) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C30%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004301106586900-5389%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kQBA1gORg1KoNirBFPb5SY3%2Fwyr66qBOW7ig6Z7A1ws%3D&st=2020-04-30T11%3A03%3A06Z&se=2020-05-31T11%3A08%3A06Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[068f455](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/068f455073975c5879b85d00b658f14e8cb13c4a)_: 

:clock10: **Pending**: waiting for processors ([14](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 14 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[068f455](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/068f455073975c5879b85d00b658f14e8cb13c4a)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C30%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004301108514001-5389%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=miZ1qLtRXdD8UtB%2FyOQeUADSQtEYcPZhonfxK%2FchI4E%3D&st=2020-04-30T11%3A04%3A47Z&se=2020-05-31T11%3A09%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
