### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[e38e233](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/e38e233f45ee610c42943b9e0bfc71e34eb5efbe)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[e38e233](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/e38e233f45ee610c42943b9e0bfc71e34eb5efbe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2793) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C24%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912241104271968-2793%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FrKP5BFcWx4dK64RmSensIEhCvuuZeZ9qM%2BpwauVtZU%3D&st=2019-12-24T11%3A00%3A17Z&se=2020-01-24T11%3A05%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[7d9d4e0](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/7d9d4e06cd6fabab9e56e168af2c3ba8f139e251)_: 

:clock10: **Pending**: waiting for processors ([16](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 16 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[7d9d4e0](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/7d9d4e06cd6fabab9e56e168af2c3ba8f139e251)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C24%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912241105351438-2793%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cgXfldc8XhEUHspXDa%2F6hWtsE2N4xH8KqIRXgpg01SU%3D&st=2019-12-24T11%3A01%3A14Z&se=2020-01-24T11%3A06%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
