### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[411c1e4](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/411c1e4d0a8fffed345fe1eff977048ae9039df8)_: 

:clock10: **Pending**: waiting for processors ([13](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 13 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[411c1e4](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/411c1e4d0a8fffed345fe1eff977048ae9039df8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-5222) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C22%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004221104211425-5222%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YvC4ZQgkqrFewz0Ciw%2Bq9UW%2BBoPKtZLl5kg%2BTvBiSMQ%3D&st=2020-04-22T11%3A00%3A02Z&se=2020-05-23T11%3A05%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[628812f](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/628812f74d3799b47c958193af1338f87aea01ae)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[628812f](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/628812f74d3799b47c958193af1338f87aea01ae)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C22%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004221105179280-5222%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NbxmR%2FkzcJt2hpgQg51d5NJQM4GdZey1J9XYLNciG8s%3D&st=2020-04-22T11%3A00%3A55Z&se=2020-05-23T11%3A05%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
