### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[2d0e89c](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/2d0e89c32ae040bfb66e268c9f10710a683199ec)_: 

:clock10: **Pending**: waiting for processors ([18](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 18 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[2d0e89c](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/2d0e89c32ae040bfb66e268c9f10710a683199ec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-5935) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C6%5C1%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202006011105306854-5935%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=u1m%2FOm%2FlS0JYr%2F9Ap%2F6imsQn25mPv6oSHVev%2BoIM6SA%3D&st=2020-06-01T11%3A01%3A17Z&se=2020-07-02T11%3A06%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://opportal-sandbox.azurewebsites.net/#/repos/8b165afe-a866-8c48-e5c3-ead94440f27e?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[bc8dbe5](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/bc8dbe57690e834f3105a87bc957aeb1fbbf4df6)_: 

:clock10: **Pending**: waiting for processors ([18](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 18 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[bc8dbe5](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/bc8dbe57690e834f3105a87bc957aeb1fbbf4df6)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C6%5C1%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202006011106272809-5935%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LYiBJUsFbGek2ZjIyrcjO%2BGO4N8kCWZOZ8nRb%2BJJzA0%3D&st=2020-06-01T11%3A02%3A01Z&se=2020-07-02T11%3A07%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://opportal-sandbox.azurewebsites.net/#/repos/8b165afe-a866-8c48-e5c3-ead94440f27e?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request closed without merging**
