### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[715e1eb](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/715e1eb1ad28f1994547b09c8594f34ff2292d82)_: 

:clock10: **Pending**: waiting for processors ([15](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 15 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[715e1eb](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/715e1eb1ad28f1994547b09c8594f34ff2292d82)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2892) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C30%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912301104315862-2892%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Jy25KxVzq7RARFeIDG8g2gy57FIDeZkQ5bndYYDMSzM%3D&st=2019-12-30T11%3A00%3A13Z&se=2020-01-30T11%3A05%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[3d5efe2](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/3d5efe256ad6286d01ee7fc5682c85349a6c8fbb)_: 

:clock10: **Pending**: waiting for processors ([15](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 15 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[3d5efe2](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/3d5efe256ad6286d01ee7fc5682c85349a6c8fbb)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C30%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912301105356247-2892%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=d0aDHVsGc24O%2F8LHbV8hg%2B3lW17C7wfk%2BjnEWb%2BW1fE%3D&st=2019-12-30T11%3A01%3A16Z&se=2020-01-30T11%3A06%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
