### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[fd4c6db](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/fd4c6db58e5aeffbbc3106db88d184dec8d0127e)_: 

:clock10: **Pending**: waiting for processors ([17](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 17 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[fd4c6db](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/fd4c6db58e5aeffbbc3106db88d184dec8d0127e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2160) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C18%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201911181102522136-2160%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YRWMGNrbjXMHcK5%2Bh6dKv8OX8%2BWR8FVxayRin2j12hk%3D&st=2019-11-18T10%3A58%3A47Z&se=2019-12-19T11%3A03%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[8db968a](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/8db968a3e2a205de5c706e8ad28c0237a95522f0)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[8db968a](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/8db968a3e2a205de5c706e8ad28c0237a95522f0)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C18%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201911181104519037-2160%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5STwjhkTQ7yuefVuvW1VCir1jG4nb9BB2YedwpPX19Q%3D&st=2019-11-18T11%3A00%3A43Z&se=2019-12-19T11%3A05%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
