### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[bfa27c5](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/bfa27c520b024c3d494e9a5969381b8dd0fb74e3)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[bfa27c5](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/bfa27c520b024c3d494e9a5969381b8dd0fb74e3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-4145) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C4%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003041103168089-4145%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=h7t2CMEoZ8fqR8QEA4dwuVp4rkhYp4m0G6vhRECBRlQ%3D&st=2020-03-04T10%3A59%3A11Z&se=2020-04-04T11%3A04%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[923b0dc](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/923b0dccbfb30709753f7710d142aa1901154838)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[923b0dc](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/923b0dccbfb30709753f7710d142aa1901154838)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C4%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003041104199848-4145%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=S44%2FGcQW%2FBABDygztCWvqF4fiarMZVv6SZ56nok5yBk%3D&st=2020-03-04T11%3A00%3A12Z&se=2020-04-04T11%3A05%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
