### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[7b889d5](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/7b889d51f30d2ccb1d91babad9000f887351e180)_: 

:clock10: **Pending**: waiting for processors ([16](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 16 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[7b889d5](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/7b889d51f30d2ccb1d91babad9000f887351e180)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-4367) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C12%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003121104128743-4367%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dn%2FYE6naooJRDytnuhm4AstLtG8hbS2FySRyUCWisOQ%3D&st=2020-03-12T10%3A59%3A50Z&se=2020-04-12T11%3A04%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[7f95a49](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/7f95a4949e396ceb55f8c393ece133a9f8c0a1b9)_: 

:clock10: **Pending**: waiting for processors ([9](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[7f95a49](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/7f95a4949e396ceb55f8c393ece133a9f8c0a1b9)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C12%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003121105214469-4367%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=r2XTGpLXIsB9UGMetgwPHsefywKUJPsSByq%2B1kENM5o%3D&st=2020-03-12T11%3A01%3A12Z&se=2020-04-12T11%3A06%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
