### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[7d60229](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/7d60229e55dd94aae69e55547059f8bfab4e06c3)_: 

:clock10: **Pending**: waiting for processors ([8](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[7d60229](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/7d60229e55dd94aae69e55547059f8bfab4e06c3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-1322) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C29%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201909291104584076-1322%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PU1Z7bwQkf45pr3GmfY6TZGVCgUWSF2AXIHqSsmxv5w%3D&st=2019-09-29T11%3A00%3A41Z&se=2019-10-30T11%3A05%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[b189cdc](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/b189cdc42f6f6431c72d3928bd5970bf6e883ff8)_: 

:clock10: **Pending**: waiting for processors ([8](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[b189cdc](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/b189cdc42f6f6431c72d3928bd5970bf6e883ff8)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C29%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201909291106039227-1322%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BRBw%2FB37MZTwAgF37bXhY2QaRDcaqonBjzs%2Bi3CyzGc%3D&st=2019-09-29T11%3A01%3A48Z&se=2019-10-30T11%3A06%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
