### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[434fabd](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/434fabd360d9413ea139c756681d95e209704639)_: 

:clock10: **Pending**: waiting for processors ([10](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[434fabd](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/434fabd360d9413ea139c756681d95e209704639)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2544) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C10%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912101102490397-2544%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cb4MOp6ay5hFzJzJw0o5fFowlIpDujxP%2Bzqyk%2BJVzaM%3D&st=2019-12-10T10%3A58%3A39Z&se=2020-01-10T11%3A03%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[ca75993](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/ca75993ed7ec0a51c397fb509866610dc0f6e2af)_: 

:clock10: **Pending**: waiting for processors ([10](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[ca75993](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/ca75993ed7ec0a51c397fb509866610dc0f6e2af)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C10%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912101103561933-2544%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qxhoMZC7VrDbns4r%2BYIQX8fTr0NRY9QWwvjyly8%2FW6A%3D&st=2019-12-10T10%3A59%3A35Z&se=2020-01-10T11%3A04%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
