### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[0f097fa](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/0f097fa2d4153d3d03908194780ecbcaa04a5309)_: 

:clock10: **Pending**: waiting for processors ([9](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[0f097fa](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/0f097fa2d4153d3d03908194780ecbcaa04a5309)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2424) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C3%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912031204364649-2424%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rpvvi9fldfB%2FzNvjQjytL9Bj3LTE%2BFNcIWmWkIVWgxw%3D&st=2019-12-03T12%3A00%3A21Z&se=2020-01-03T12%3A05%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[bd41fc2](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/bd41fc2bd12be978b1c887ef0e1bdcb34b0e2087)_: 

:clock10: **Pending**: waiting for processors ([9](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[bd41fc2](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/bd41fc2bd12be978b1c887ef0e1bdcb34b0e2087)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C3%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912031205493163-2424%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VuFNQ4kZiprqO6gYcylEFPLf2nr%2BmEUFkaAqRnYM5cw%3D&st=2019-12-03T12%3A01%3A33Z&se=2020-01-03T12%3A06%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
