### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[ec55cb3](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/ec55cb3e9377e9548e079c805bb9facc15119c3b)_: 

:clock10: **Pending**: waiting for processors ([16](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 16 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[ec55cb3](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/ec55cb3e9377e9548e079c805bb9facc15119c3b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-3499) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C30%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001301105286554-3499%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=waLAluIcb1V1XIzeaxbUQuPj1UyBrwUK1qe8a2bXP4U%3D&st=2020-01-30T11%3A01%3A22Z&se=2020-03-01T11%3A06%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[5a34558](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/5a3455801e1501cc9d870c4ec0b7af03f71208ea)_: 

:clock10: **Pending**: waiting for processors ([10](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[5a34558](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/5a3455801e1501cc9d870c4ec0b7af03f71208ea)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C30%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001301106362883-3499%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=k0nFGRvN8nZFM4OeMX%2BSg5CuhEPhXcpSTiQDNJFyDnY%3D&st=2020-01-30T11%3A02%3A18Z&se=2020-03-01T11%3A07%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
