### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[0815333](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/0815333011a023bba15e997bad39dc35a109de89)_: 

:clock10: **Pending**: waiting for processors ([7](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 7 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[0815333](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/0815333011a023bba15e997bad39dc35a109de89)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2473) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C5%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912051153020920-2473%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=k3JUbdeMseph%2FYVTQqn6w2o4JgVyMU8zjcCVMsaVXLw%3D&st=2019-12-05T11%3A48%3A45Z&se=2020-01-05T11%3A53%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[b69666e](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/b69666ec96842a32d8758bed4b4ecfac487c14c6)_: 

:clock10: **Pending**: waiting for processors ([7](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 7 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[b69666e](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/b69666ec96842a32d8758bed4b4ecfac487c14c6)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C5%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912051153587539-2473%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CldF%2BUDZJLcB%2FAWqD3o2hJm5%2BIZsi52%2BNdnPVU4anYs%3D&st=2019-12-05T11%3A49%3A36Z&se=2020-01-05T11%3A54%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
