### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[12dfc53](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/12dfc5310f7b9fc579075c3a70aaa865ba54498f)_: 

:clock10: **Pending**: waiting for processors ([6](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[12dfc53](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/12dfc5310f7b9fc579075c3a70aaa865ba54498f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-3034) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C6%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001061104205995-3034%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7VL%2F1H%2BHN5WbN80eH%2BSrKE8V3uqduStMgyh%2BxtPd7eg%3D&st=2020-01-06T11%3A00%3A17Z&se=2020-02-06T11%3A05%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[9ae76e3](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9ae76e3d192fe4338f9ca911f438a8946acb9f1a)_: 

:clock10: **Pending**: waiting for processors ([8](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[9ae76e3](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9ae76e3d192fe4338f9ca911f438a8946acb9f1a)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C6%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001061105245164-3034%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TOE2rP25wyY8iwwM%2FsnDnEiUNwToMvGwljFEs5iGMZ8%3D&st=2020-01-06T11%3A01%3A02Z&se=2020-02-06T11%3A06%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
