### PR TITLE
Incremental PR: add a resource and delete the added resource

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[a84fc68](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/a84fc68782ad852e966eb5fafb7b6db317fc38ae)_: 

:clock10: **Pending**: waiting for processors ([5](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[a84fc68](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/a84fc68782ad852e966eb5fafb7b6db317fc38ae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/incrementalPR-addresource.jpg](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addresource/E2E_DocsBranch_Dynamic/incrementalPR-addresource.jpg) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/incrementalpr-addresource.jpg?branch=pr-en-us-1337) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C29%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201909291117551778-1337%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TxK8E7I4j2TcJrW5dfO2wciogoPYt05nRD51szMQ8r0%3D&st=2019-09-29T11%3A14%3A46Z&se=2019-10-30T11%3A19%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[b15fdee](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/b15fdeeb71182ff0a9a409063b4643cd6b6dbd84)_: 

:clock10: **Pending**: waiting for processors ([5](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[b15fdee](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/b15fdeeb71182ff0a9a409063b4643cd6b6dbd84)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-49753403)

<a id="49753403"></a>
###
 - **[Error]** `````Run script failed with no detailed information. Please retry building your content again. If the issue still happens, open a ticket in http://SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C29%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201909291120203752-1337%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OKfFjvGKdpMT1otDYQakpPQmmT9R6yFuViu00iqQMw8%3D&st=2019-09-29T11%3A16%3A03Z&se=2019-10-30T11%3A21%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
