### PR TITLE
Incremental PR: add a resource and delete the added resource

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[e63e9bc](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/e63e9bcf074287483aeefa2405e7f84074a4ce55)_: 

:clock10: **Pending**: waiting for processors ([6](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[e63e9bc](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/e63e9bcf074287483aeefa2405e7f84074a4ce55)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/incrementalPR-addresource.jpg](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addresource/E2E_DocsBranch_Dynamic/incrementalPR-addresource.jpg) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/incrementalpr-addresource.jpg?branch=pr-en-us-1307) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C25%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201909251117202720-1307%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=k5rqJLhV3CjNeUmsqTqoIzW2s0jurDztAxJpEcZ2xoY%3D&st=2019-09-25T11%3A12%3A50Z&se=2019-10-26T11%3A17%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[717fc7e](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/717fc7e0408b372574e9abd88dacbf036df42dcb)_: 

:clock10: **Pending**: waiting for processors ([6](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[717fc7e](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/717fc7e0408b372574e9abd88dacbf036df42dcb)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C25%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201909251118261135-1307%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=L5M4YsplMr5rBfd%2BCBphgVilvTC5%2BCHycsVubBJYAxg%3D&st=2019-09-25T11%3A13%3A59Z&se=2019-10-26T11%3A18%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
