### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[3e05e8c](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/3e05e8cd4bb712b6a57dbb6a6c881ef0c81ff534)_: 

:clock10: **Pending**: waiting for processors ([16](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 16 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[3e05e8c](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/3e05e8cd4bb712b6a57dbb6a6c881ef0c81ff534)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-4394) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C15%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003151105442888-4394%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=anURREOv6Srz8j8EpImV%2BDYuKqzXbXKKjDJzt6g3pZ0%3D&st=2020-03-15T11%3A01%3A26Z&se=2020-04-15T11%3A06%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[6756cd0](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/6756cd0dbe4571971202a36dcd6157ed79472a69)_: 

:clock10: **Pending**: waiting for processors ([8](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[6756cd0](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/6756cd0dbe4571971202a36dcd6157ed79472a69)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C15%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003151106506221-4394%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=w274UwLCmaN4cFCCwnkSvwiFRX40JVJRj1HLJlYs9hs%3D&st=2020-03-15T11%3A02%3A45Z&se=2020-04-15T11%3A07%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
