### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[be55b41](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/be55b41d630eb1bee3a6cec81a5feffd073d071e)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[be55b41](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/be55b41d630eb1bee3a6cec81a5feffd073d071e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-9457) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C10%5C5%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202010051103116766-9457%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TYzaSk4S4kOrm6TdxtKe0PA5VeiBggR5KdooThdRO10%3D&st=2020-10-05T10%3A58%3A44Z&se=2020-11-05T11%3A03%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://opportal-sandbox.azurewebsites.net/#/repos/8b165afe-a866-8c48-e5c3-ead94440f27e?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[75a4b90](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/75a4b90ac945c9f3f77fa053af605aadf4e4f56a)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[75a4b90](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/75a4b90ac945c9f3f77fa053af605aadf4e4f56a)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C10%5C5%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202010051104118174-9457%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=t%2FgAJ%2F7t8HIUNKLQs%2F3PCCw3JMCVQ%2BKkj5OCCgkxPpw%3D&st=2020-10-05T10%3A59%3A47Z&se=2020-11-05T11%3A04%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://opportal-sandbox.azurewebsites.net/#/repos/8b165afe-a866-8c48-e5c3-ead94440f27e?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request closed without merging**
