### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[aaf1919](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/aaf1919b4fcfef9c6f814f82eb5817da7e0bb7c2)_: 

:clock10: **Pending**: waiting for processors ([10](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[aaf1919](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/aaf1919b4fcfef9c6f814f82eb5817da7e0bb7c2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2597) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C12%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912121141245752-2597%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lZKLy%2B%2F1%2FlQGmvIO38doh188%2BE%2B7ADVCGwDbqsLHOwI%3D&st=2019-12-12T11%3A37%3A08Z&se=2020-01-12T11%3A42%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[2405139](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/2405139d6764fca1fde4fec84617f2e804aedf89)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[2405139](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/2405139d6764fca1fde4fec84617f2e804aedf89)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C12%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912121142335644-2597%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=D%2Fah5dng7fPTjEOz38QJIG45VQdMJRxtGjnv0TBg958%3D&st=2019-12-12T11%3A38%3A17Z&se=2020-01-12T11%3A43%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
