### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[cb1b12e](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/cb1b12e2f70a8251613963ef706c3f3216364f38)_: 

:clock10: **Pending**: waiting for processors ([16](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 16 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[cb1b12e](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/cb1b12e2f70a8251613963ef706c3f3216364f38)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-5111) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C16%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004161105582004-5111%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vGWHqTD0bI7q%2FB5K2BLLAVeVFtX8JmXQBLo8UAYWDW4%3D&st=2020-04-16T11%3A01%3A37Z&se=2020-05-17T11%3A06%3A37Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[241a178](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/241a1780a4ca924a5de79ff42e40a233417c59b9)_: 

:clock10: **Pending**: waiting for processors ([19](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 19 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[241a178](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/241a1780a4ca924a5de79ff42e40a233417c59b9)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C16%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004161106592110-5111%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2JnsNiROIPYS8Kbgn1YBwof49nQnyxdrYzuaa%2B9a9Fw%3D&st=2020-04-16T11%3A02%3A32Z&se=2020-05-17T11%3A07%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
