### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[b5951a4](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/b5951a4514608941b4ec91f53fd4dcce55b9714e)_: 

:clock10: **Pending**: waiting for processors ([19](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 19 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[b5951a4](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/b5951a4514608941b4ec91f53fd4dcce55b9714e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-4743) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C2%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004021105024767-4743%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HTGHYlZ3zrn2Kop1fjnY8F9CJL3M55gdlh5gqaCiJY8%3D&st=2020-04-02T11%3A01%3A13Z&se=2020-05-03T11%3A06%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[8399eb6](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/8399eb652645bb385dc402d7f73fa594822f42f7)_: 

:clock10: **Pending**: waiting for processors ([8](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[8399eb6](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/8399eb652645bb385dc402d7f73fa594822f42f7)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C2%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004021107049497-4743%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UWG%2FVxvmDT11VI5Fe9d1ZmgflD5rVJOQrTlyiOOVN3o%3D&st=2020-04-02T11%3A02%3A44Z&se=2020-05-03T11%3A07%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
