### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[2e04e16](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/2e04e1623f454447a0009452b9c3b8cfd5104cd0)_: 

:clock10: **Pending**: waiting for processors ([5](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[2e04e16](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/2e04e1623f454447a0009452b9c3b8cfd5104cd0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-3899) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C2%5C20%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202002201104245517-3899%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=B%2B882qkEyR6%2FgvymH9pM7In439O4mIB1xIk1wReirJQ%3D&st=2020-02-20T11%3A00%3A19Z&se=2020-03-22T11%3A05%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[ded4848](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/ded48488a2370bc440b83460cc44a04910312864)_: 

:clock10: **Pending**: waiting for processors ([8](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[ded4848](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/ded48488a2370bc440b83460cc44a04910312864)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C2%5C20%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202002201105358294-3899%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Y0m5RiWYNwW68L7C43FWSkCdc2DBnUDZQ7Amh45VyLM%3D&st=2020-02-20T11%3A01%3A18Z&se=2020-03-22T11%3A06%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
