### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[bb5e544](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/bb5e544ff0cee5137870c24d30bac3f6df7328e4)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[bb5e544](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/bb5e544ff0cee5137870c24d30bac3f6df7328e4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-3999) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C2%5C26%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202002261105289586-3999%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RHXxswMdjk7ey%2FIvezRjsT2jjUJBV3%2FV9Tv4KBvkkWo%3D&st=2020-02-26T11%3A01%3A18Z&se=2020-03-28T11%3A06%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[3b90dd0](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/3b90dd0a899db61ed971377fe2714ed7ca1f54fa)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[3b90dd0](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/3b90dd0a899db61ed971377fe2714ed7ca1f54fa)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C2%5C26%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202002261106376096-3999%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bGdJU6%2FdcfyAdFlMSiD0BFTGMUDuw5qsdAba%2BH5o3Vs%3D&st=2020-02-26T11%3A02%3A20Z&se=2020-03-28T11%3A07%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
