### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[df31ef6](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/df31ef685b930259b3bc1176888a2998abe3fade)_: 

:clock10: **Pending**: waiting for processors ([6](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[df31ef6](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/df31ef685b930259b3bc1176888a2998abe3fade)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-4518) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C22%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003221103273747-4518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aRGZVRhOuOVJzpszkvJrkPFsl%2FQCfMg1fikWBo1JvUQ%3D&st=2020-03-22T10%3A59%3A07Z&se=2020-04-22T11%3A04%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[b5c6cf3](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/b5c6cf36ca7d8cc0da093c10ad1d5cdadc1df6ec)_: 

:clock10: **Pending**: waiting for processors ([10](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[b5c6cf3](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/b5c6cf36ca7d8cc0da093c10ad1d5cdadc1df6ec)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C3%5C22%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202003221104297446-4518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BWJLAnoUG0URjxNkW4ePNbK5v3jNTgPCSDH2PAD7gJg%3D&st=2020-03-22T11%3A00%3A23Z&se=2020-04-22T11%3A05%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
