### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[3a1c0ed](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/3a1c0ed2b2351685771835b5bc704f8e91b096b3)_: 

:clock10: **Pending**: waiting for processors ([15](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 15 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[3a1c0ed](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/3a1c0ed2b2351685771835b5bc704f8e91b096b3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-1912) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C6%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201911060113013230-1912%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5cPPXDLRxee9DopVqQ9kx9OJ68AdMMt9Ang86UQzdV8%3D&st=2019-11-06T01%3A09%3A03Z&se=2019-12-07T01%3A14%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[6cbfc50](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/6cbfc503b3611699a9c048c8f13c1cb551168613)_: 

:clock10: **Pending**: waiting for processors ([7](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 7 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[6cbfc50](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/6cbfc503b3611699a9c048c8f13c1cb551168613)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C6%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201911060114586604-1912%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BU1Z3iDkOayu9ACkuHpvQblkMf0KxVywRDOffRyvaws%3D&st=2019-11-06T01%3A10%3A35Z&se=2019-12-07T01%3A15%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
