### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[1bdc170](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/1bdc17041510e59add5207a7933c2a908947cb77)_: 

:clock10: **Pending**: waiting for processors ([16](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 16 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[1bdc170](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/1bdc17041510e59add5207a7933c2a908947cb77)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-5737) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C5%5C21%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202005211108367548-5737%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FsKTtGVG7bsaxn%2BWZD302JKwF5RkCwBlcIu%2B4mD%2BRqY%3D&st=2020-05-21T11%3A04%3A25Z&se=2020-06-21T11%3A09%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[c09e06c](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/c09e06c46c87ebed6e6acdd65e58d55746a27352)_: 

:clock10: **Pending**: waiting for processors ([16](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 16 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[c09e06c](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/c09e06c46c87ebed6e6acdd65e58d55746a27352)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C5%5C21%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202005211109348053-5737%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5SVpXop499Q3kmRSGRlrQM3jnYXkMzfxLX4GN%2FetSLc%3D&st=2020-05-21T11%3A05%3A43Z&se=2020-06-21T11%3A10%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
