### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[1f5ccab](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/1f5ccabbedcc9df026462b23af39567cabbad0d8)_: 

:clock10: **Pending**: waiting for processors ([6](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[1f5ccab](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/1f5ccabbedcc9df026462b23af39567cabbad0d8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-5306) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C27%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004271103179754-5306%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=o88Vfo2Fo9FXEn1SUxw0lQ2riNTweaLY51RvhloysrA%3D&st=2020-04-27T10%3A58%3A52Z&se=2020-05-28T11%3A03%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[71dc225](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/71dc2251dba3385ac359422522ac14e2b4988bbf)_: 

:clock10: **Pending**: waiting for processors ([6](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[71dc225](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/71dc2251dba3385ac359422522ac14e2b4988bbf)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C27%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004271104229623-5306%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=u1zVsEncuo%2FTKmiPrrWHRnVdzaXgECZam5EwYbDzyrQ%3D&st=2020-04-27T11%3A00%3A23Z&se=2020-05-28T11%3A05%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
