### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[2dca612](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/2dca612216fbd15aa7c6013535ab9f1ff799e5e0)_: 

:clock10: **Pending**: waiting for processors ([10](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[2dca612](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/2dca612216fbd15aa7c6013535ab9f1ff799e5e0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-4804) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C6%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004060820469921-4804%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Qx1nQe3lFeyyOu%2F62DlKwoCvttA72KRuFI3OKAGWvPE%3D&st=2020-04-06T08%3A16%3A21Z&se=2020-05-07T08%3A21%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[c65d967](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/c65d9675f48dc9dd088490401ea16fb98377e761)_: 

:clock10: **Pending**: waiting for processors ([10](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[c65d967](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/c65d9675f48dc9dd088490401ea16fb98377e761)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C6%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004060821504753-4804%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WZQhlvIRmMCvjBJ66mW%2Fy6yfxqcKPcscD3DrVD4EoaU%3D&st=2020-04-06T08%3A17%3A24Z&se=2020-05-07T08%3A22%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
