### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[b451a72](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/b451a72d730c0dcf1386b364d0d635c684cf566c)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[b451a72](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/b451a72d730c0dcf1386b364d0d635c684cf566c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-1193) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C17%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201909171102343134-1193%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=01C1Etgpb06Rehx2oMfQdw9zPkO81WU2dhogXuRXRWI%3D&st=2019-09-17T10%3A58%3A11Z&se=2019-10-18T11%3A03%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[1ae5e04](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/1ae5e042460410b87f141eb444f9ba3f2d129fc4)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[1ae5e04](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/1ae5e042460410b87f141eb444f9ba3f2d129fc4)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C17%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201909171103417956-1193%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pjXjcffA1XOnmp0XlpzKj%2BlMTDgmnab5ky3b7Fn22HM%3D&st=2019-09-17T10%3A59%3A17Z&se=2019-10-18T11%3A04%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
