### PR TITLE
Incremental PR: add a resource and delete the added resource

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by v-minnli** [comment]
Docs Build status updates of commit _[1c3d4d0](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/1c3d4d08522e1704d9d9c3c2786b77b70ebacbf8)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by v-minnli** [comment]
Docs Build status updates of commit _[1c3d4d0](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/1c3d4d08522e1704d9d9c3c2786b77b70ebacbf8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[E2E_DocsBranch_Dynamic/incrementalPR-addresource.jpg](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addresource/E2E_DocsBranch_Dynamic/incrementalPR-addresource.jpg) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/incrementalpr-addresource.jpg?branch=pr-en-us-928) | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C8%5C19%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201908191818133326-928%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FDwVFMloKSCsyH6EbHGbiRrEhTxTeO8TlaXUkhPhn1M%3D&st=2019-08-19T18%3A13%3A47Z&se=2019-09-19T18%3A18%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[e75c241](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/e75c2410e3d7ca1bb9b323d356d00a48d79bdd00)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[e75c241](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/e75c2410e3d7ca1bb9b323d356d00a48d79bdd00)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C8%5C19%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201908191819197733-928%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=P8jyTRA%2Bm4gyCM1d7fjfFl%2BLGzLdzg0CykOBN1BhBqk%3D&st=2019-08-19T18%3A14%3A53Z&se=2019-09-19T18%3A19%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
