### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[40d2aba](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/40d2aba9e18000a26056f7bc7a176bb24164adca)_: 

:clock10: **Pending**: waiting for processors ([8](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[40d2aba](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/40d2aba9e18000a26056f7bc7a176bb24164adca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2844) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C26%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912261105274485-2844%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DY4Iv3IDONx9PT4xrIABWXcw2%2FvofWw6NksK6O6gECs%3D&st=2019-12-26T11%3A01%3A06Z&se=2020-01-26T11%3A06%3A06Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[1bb9819](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/1bb981918158bd838056be6147b8133e179c9c78)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[1bb9819](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/1bb981918158bd838056be6147b8133e179c9c78)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C26%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912261106322239-2844%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=L8LDh5ofahRir%2BZf9jHTaaTb%2FGWocYm3gHMDXWyTkFM%3D&st=2019-12-26T11%3A02%3A36Z&se=2020-01-26T11%3A07%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
