### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[6aab200](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/6aab200ebc4cc2c45cd25bd964a87fd1608c0c18)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[6aab200](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/6aab200ebc4cc2c45cd25bd964a87fd1608c0c18)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-3427) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C27%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001271105232368-3427%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oynD3nOrJNA%2BZNmWQacXXGP2PpQ0a14oStU6p01b4tw%3D&st=2020-01-27T11%3A01%3A12Z&se=2020-02-27T11%3A06%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[6dbff68](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/6dbff68b3b6473d78a666fdc964054027510335c)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[6dbff68](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/6dbff68b3b6473d78a666fdc964054027510335c)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C27%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001271106264408-3427%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cAsuqWhYjPRedSIH13rup25kN1mSbyaX8T7wo9ysOcc%3D&st=2020-01-27T11%3A02%3A11Z&se=2020-02-27T11%3A07%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
