### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[ee6a910](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/ee6a9104a192763e7a5912e2be83255ce8ad30c3)_: 

:clock10: **Pending**: waiting for processors ([6](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[ee6a910](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/ee6a9104a192763e7a5912e2be83255ce8ad30c3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-1482) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C9%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201910091104566884-1482%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FzAaqXOf5eimUEVyOpF8MO9UrucOkgtEFw0%2B91qkMNU%3D&st=2019-10-09T11%3A00%3A31Z&se=2019-11-09T11%3A05%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[154d560](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/154d5604b4adf766353a90446110beb53d0ad9e0)_: 

:clock10: **Pending**: waiting for processors ([6](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[154d560](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/154d5604b4adf766353a90446110beb53d0ad9e0)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C9%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201910091106028965-1482%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0vCJrZpXOFB1LnQzvLMOY7K3rri3ThnB7H2vv7Mt4A0%3D&st=2019-10-09T11%3A01%3A38Z&se=2019-11-09T11%3A06%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
