### PR TITLE
Incremental PR: add a resource and delete the added resource

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[824d6d7](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/824d6d749bac935ede1f21dd586c6fc4885b20d9)_: 

:clock10: **Pending**: waiting for processors ([9](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[824d6d7](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/824d6d749bac935ede1f21dd586c6fc4885b20d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/incrementalPR-addresource.jpg](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addresource/E2E_DocsBranch_Dynamic/incrementalPR-addresource.jpg) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/incrementalpr-addresource.jpg?branch=pr-en-us-3083) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C7%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001071212418174-3083%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IrjB5a4Qej1198OQffqKSVfPpHRUp%2BBFMHurgnT1ARM%3D&st=2020-01-07T12%3A08%3A40Z&se=2020-02-07T12%3A13%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[e1df19c](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/e1df19c079761a22b06956b78e2643dc411f3cf6)_: 

:clock10: **Pending**: waiting for processors ([8](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[e1df19c](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/e1df19c079761a22b06956b78e2643dc411f3cf6)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C7%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001071214453173-3083%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DqNyESLAd2ad3Jr6vzqIzD0%2B4F0Hu4qTpbr3j8fwFPo%3D&st=2020-01-07T12%3A10%3A48Z&se=2020-02-07T12%3A15%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
