### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[43d77cb](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/43d77cbad3f256079f14e93e67e3f65be8b4928d)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[43d77cb](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/43d77cbad3f256079f14e93e67e3f65be8b4928d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2720) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C19%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912191105227667-2720%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Z9yk63fAp9GD7ONEM3idklXlVxTZck3gMJeRhT%2B6Z2M%3D&st=2019-12-19T11%3A01%3A11Z&se=2020-01-19T11%3A06%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[5271252](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/5271252069b45fa55951d8328c68fb09b661d767)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[5271252](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/5271252069b45fa55951d8328c68fb09b661d767)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C19%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912191106255215-2720%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RkUIKw9xgK3bzE301W0RwwDBDMaMLOwUJc2wWCq%2Bj0I%3D&st=2019-12-19T11%3A02%3A05Z&se=2020-01-19T11%3A07%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
