### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[9b13aa6](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9b13aa65596a32042ea2932b2e642ee5bcb979ac)_: 

:clock10: **Pending**: waiting for processors ([15](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 15 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[9b13aa6](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9b13aa65596a32042ea2932b2e642ee5bcb979ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2643) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C16%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912161103022542-2643%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LbM3BfFvCj8J32EQhrEXWXShi7ZnrU3E313s36aBiDM%3D&st=2019-12-16T10%3A59%3A10Z&se=2020-01-16T11%3A04%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[9f6f335](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9f6f3353ad11e9ce0637e51a208a47c5e180194c)_: 

:clock10: **Pending**: waiting for processors ([13](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 13 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[9f6f335](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9f6f3353ad11e9ce0637e51a208a47c5e180194c)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C16%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912161105064618-2643%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=u%2FAa4daYUOgPylB7PGCoyEWVLrhE3DZf1IMQwYfnaCM%3D&st=2019-12-16T11%3A00%3A45Z&se=2020-01-16T11%3A05%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
