### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[8663092](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/866309264eb8fde203303d63db6910615f719e99)_: 

:clock10: **Pending**: waiting for processors ([6](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[8663092](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/866309264eb8fde203303d63db6910615f719e99)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2620) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C15%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912151103318357-2620%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rvyKv0NHc4VN%2F8VNLl7XW7t%2BEu2xmENNHvxnqEcKCTM%3D&st=2019-12-15T10%3A59%3A41Z&se=2020-01-15T11%3A04%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[08cc47d](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/08cc47d98ae944416626948d96b39dd9fd37206d)_: 

:clock10: **Pending**: waiting for processors ([9](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[08cc47d](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/08cc47d98ae944416626948d96b39dd9fd37206d)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C15%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912151105298362-2620%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JKL5C5o%2FkbfLHtMwiVoh4HqQQhpKZIzlrcR%2FlR08unE%3D&st=2019-12-15T11%3A01%3A11Z&se=2020-01-15T11%3A06%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
