### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[a403619](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/a40361975e9e0b9a6e979dc73fdc33f13ed1541e)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[a403619](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/a40361975e9e0b9a6e979dc73fdc33f13ed1541e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2057) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C11%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201911111103108550-2057%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZzySS8Z%2B8WpdVvPPP6lDQBP2VzqH2K2Js1OMcveui6g%3D&st=2019-11-11T10%3A58%3A49Z&se=2019-12-12T11%3A03%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[ba6afb5](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/ba6afb5455cbb3a0d6e9c1952bbfeefda4bb2a42)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[ba6afb5](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/ba6afb5455cbb3a0d6e9c1952bbfeefda4bb2a42)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C11%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201911111104218918-2057%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FPElFLnDy4Cu3HCwweTkYql6M%2FeWR5enaKLxqjLVqqM%3D&st=2019-11-11T11%3A00%3A05Z&se=2019-12-12T11%3A05%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
