### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[5b8fe41](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/5b8fe41e0ce9c5bdee8a468a2235c52dbe0856c6)_: 

:clock10: **Pending**: waiting for processors ([14](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 14 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[5b8fe41](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/5b8fe41e0ce9c5bdee8a468a2235c52dbe0856c6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-3355) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C22%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001221105217364-3355%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=n4wfUjVSCgqrvj1BHQ%2BeuDlfArY1ahViqquiqXuNk74%3D&st=2020-01-22T11%3A01%3A08Z&se=2020-02-22T11%3A06%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[ad10a38](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/ad10a383cff7a7f0435342ab958974f0f564350f)_: 

:clock10: **Pending**: waiting for processors ([14](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 14 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[ad10a38](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/ad10a383cff7a7f0435342ab958974f0f564350f)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C22%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001221106254795-3355%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kUPOpQLH7hUSLX8OnUCcHwhUc4kYSYut0%2BQLjyamJxc%3D&st=2020-01-22T11%3A02%3A08Z&se=2020-02-22T11%3A07%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
