### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[669531e](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/669531eb2e0411823e3f37c377e0eb8938de3146)_: 

:clock10: **Pending**: waiting for processors ([25](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 25 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[669531e](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/669531eb2e0411823e3f37c377e0eb8938de3146)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-5590) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C5%5C14%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202005141106492548-5590%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FMQaQCBi5RzcgXTerdRIUUaAwB8Qy6QclZeiZ5mvxwE%3D&st=2020-05-14T11%3A02%3A49Z&se=2020-06-14T11%3A07%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[1004020](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/1004020d55503acc98d603e07b3c40741a42948e)_: 

:clock10: **Pending**: waiting for processors ([24](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 24 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[1004020](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/1004020d55503acc98d603e07b3c40741a42948e)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C5%5C14%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202005141108481352-5590%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=imVV26jHxsTqCiulwzhoHByEGJEOdzS5B4r9jILt6z8%3D&st=2020-05-14T11%3A05%3A08Z&se=2020-06-14T11%3A10%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
