### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[4ebc220](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/4ebc2206cd16ac99b5b3534812df243dbf169ef4)_: 

:clock10: **Pending**: waiting for processors ([9](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[4ebc220](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/4ebc2206cd16ac99b5b3534812df243dbf169ef4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-3257) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C16%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001161103329520-3257%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eZ9phxX9a%2FMQwxqzdpBd9pcKUHv06zecVqZtkSjuwTw%3D&st=2020-01-16T10%3A59%3A40Z&se=2020-02-16T11%3A04%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[5e482b2](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/5e482b245cd70c05750167fb78df7488c1e38ad7)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[5e482b2](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/5e482b245cd70c05750167fb78df7488c1e38ad7)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C16%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001161105292067-3257%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UW9GcSZyKLwWrlo7ra64mzztX%2FRYO%2FD50EpDuYRlM%2Bo%3D&st=2020-01-16T11%3A01%3A25Z&se=2020-02-16T11%3A06%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
