### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[f6b31bc](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/f6b31bc9a2be3b2f5f36f4b7fc13f2cf19375419)_: 

:clock10: **Pending**: waiting for processors ([19](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 19 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[f6b31bc](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/f6b31bc9a2be3b2f5f36f4b7fc13f2cf19375419)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-5709) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C5%5C20%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202005201109204016-5709%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aAJkWcgLV22RECNbe1y9UzRYATSSsJ%2FamASAvNqUK%2FY%3D&st=2020-05-20T11%3A05%3A20Z&se=2020-06-20T11%3A10%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[dc71f67](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/dc71f67353bc5cf57b0f1d6d21e7d65cdd68f277)_: 

:clock10: **Pending**: waiting for processors ([15](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 15 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[dc71f67](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/dc71f67353bc5cf57b0f1d6d21e7d65cdd68f277)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C5%5C20%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202005201111287548-5709%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ygLi8RUTOuKa0jWOQbLjjo1A%2BWkTAt%2FZuE0ZapuvwAI%3D&st=2020-05-20T11%3A07%3A30Z&se=2020-06-20T11%3A12%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
