### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[8bd77a8](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/8bd77a8e8cf0c2ba676ed3f625c5b13c260a2572)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[8bd77a8](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/8bd77a8e8cf0c2ba676ed3f625c5b13c260a2572)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2939) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C1%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001011104146840-2939%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YOdWM2PTwEMJ7aftp1d4OUVgvW%2FTIQDonCDDj54FaIo%3D&st=2020-01-01T10%3A59%3A49Z&se=2020-02-01T11%3A04%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[c632695](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/c63269519a33f134815e42dc9b4c1896cd3f1ced)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[c632695](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/c63269519a33f134815e42dc9b4c1896cd3f1ced)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C1%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001011105182713-2939%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=avDZCieJChkdshQSTOfQmlZLDfccBITSkM9OmxX%2BKpk%3D&st=2020-01-01T11%3A01%3A02Z&se=2020-02-01T11%3A06%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
