### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[6ba0ef6](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/6ba0ef6f8a31eabb8ddffe0832f3689197c7bf41)_: 

:clock10: **Pending**: waiting for processors ([10](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[6ba0ef6](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/6ba0ef6f8a31eabb8ddffe0832f3689197c7bf41)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-3163) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C12%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001121104383237-3163%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Q9CwxvjU%2BsKGIko5tVV5zYKC0LUq7cEAJoXOxywZEdY%3D&st=2020-01-12T11%3A00%3A28Z&se=2020-02-12T11%3A05%3A28Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[722d5f7](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/722d5f7022787842cf3cc47b8842f851c01e2bf1)_: 

:clock10: **Pending**: waiting for processors ([10](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[722d5f7](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/722d5f7022787842cf3cc47b8842f851c01e2bf1)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C1%5C12%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202001121105426098-3163%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TiiHwExnovrrmGDMSk4VMxN%2FdDZwq6y9KnQg1V6SxCI%3D&st=2020-01-12T11%3A01%3A16Z&se=2020-02-12T11%3A06%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
