### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[1c69cd8](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/1c69cd8d53936eecd0d63826c184676e94a01fa5)_: 

:clock10: **Pending**: waiting for processors ([11](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[1c69cd8](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/1c69cd8d53936eecd0d63826c184676e94a01fa5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-2695) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C18%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912181109550801-2695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=a9%2BkVxriWmC%2B91T8RtK3RSzhSHxk01WRI4u8vW6cvKc%3D&st=2019-12-18T11%3A05%3A36Z&se=2020-01-18T11%3A10%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[33e9705](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/33e97059e5ef900db5313aa8e6fdaf0c2075fa11)_: 

:clock10: **Pending**: waiting for processors ([5](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[33e9705](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/33e97059e5ef900db5313aa8e6fdaf0c2075fa11)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C12%5C18%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C201912181111084155-2695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1YRonchW%2BHQfTD4fCQLwJNnkwKFMRPUghsDU8ES8aZ4%3D&st=2019-12-18T11%3A07%3A06Z&se=2020-01-18T11%3A12%3A06Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
