### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[9f2f995](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9f2f995a6008bc2791f2137afbdc73dc8dd90aca)_: 

:clock10: **Pending**: waiting for processors ([18](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 18 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[9f2f995](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/9f2f995a6008bc2791f2137afbdc73dc8dd90aca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-3670) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C2%5C10%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202002101103158323-3670%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=T7b%2FL46XIH83m1kmeFDWbeflHsAwaVIc6Ncpx4IZNf8%3D&st=2020-02-10T10%3A59%3A05Z&se=2020-03-12T11%3A04%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[f7bdd3f](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/f7bdd3fbf5db7295594622f774049031ff876dd8)_: 

:clock10: **Pending**: waiting for processors ([22](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 22 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[f7bdd3f](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/f7bdd3fbf5db7295594622f774049031ff876dd8)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C2%5C10%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202002101105109066-3670%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=elDTlyJ7o1XSks%2FaedXy8oIsBz75xaoFLdOLlNwuzbc%3D&st=2020-02-10T11%3A00%3A55Z&se=2020-03-12T11%3A05%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
