### PR TITLE
Incremental PR: Add content and delete added content

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[da30f69](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/da30f694bc065eeef6d7932ed3e089ae4a91d227)_: 

:clock10: **Pending**: waiting for processors ([19](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 19 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[da30f69](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/da30f694bc065eeef6d7932ed3e089ae4a91d227)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/addcontent.md](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/blob/e2e-v3-pr-addcontent/E2E_DocsBranch_Dynamic/addcontent.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocFxV3/addcontent?branch=pr-en-us-5141) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C20%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004200116059782-5141%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Y6voB0UOb9siOWOyBCSTQGuTDc%2BklLGl%2Fpx9z7QZCJg%3D&st=2020-04-20T01%3A11%3A39Z&se=2020-05-21T01%3A16%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[fc06a8d](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/fc06a8d304fc892ae7e54a88cbe44353fcdd77f1)_: 

:clock10: **Pending**: waiting for processors ([13](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 13 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[fc06a8d](https://github.com/OPS-E2E-PPE/E2E_DocFxV3/commits/fc06a8d304fc892ae7e54a88cbe44353fcdd77f1)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C4%5C20%5C8b165afe-a866-8c48-e5c3-ead94440f27e%5CPullRequest%5C202004200117077454-5141%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FneTX88v%2BxvQ%2BlXse1xWos7XckgRbu5kQAFHdG4K0Bc%3D&st=2020-04-20T01%3A12%3A41Z&se=2020-05-21T01%3A17%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
